In [1]:
from dotenv import load_dotenv
from googleapiclient.discovery import build
import os,json

In [2]:
load_dotenv()

True

In [3]:
api_key=os.getenv('API_KEY')

In [4]:
yt=build('youtube','v3',developerKey=api_key)

In [86]:
ch_test_id='UCPbUTEjdU04ChIZfi53jczw'

In [87]:
request=yt.channels().list(
    part='snippet',
    id=ch_test_id
)

In [89]:
response=request.execute()

In [90]:
text=json.dumps(response,indent=4)

In [91]:
print(text)

{
    "kind": "youtube#channelListResponse",
    "etag": "a7XcqQaYAOSqAWBRzUCfAqAhuSU",
    "pageInfo": {
        "totalResults": 1,
        "resultsPerPage": 5
    },
    "items": [
        {
            "kind": "youtube#channel",
            "etag": "7CSZI7F_77T81JQFP7dHsAYmGII",
            "id": "UCPbUTEjdU04ChIZfi53jczw",
            "snippet": {
                "title": "G M Dance Centre",
                "description": "Hi, Welcome to our Channel. \nWe will be uploading Dance Videos/Tutorials of different dance styles for all age groups. \nSubscribe to our channel to get the latest updates.\n\nFor business inquiry \nMail: gmdcindia@gmail.com \nWhatsapp +91-9990029978\n.\n\ud83d\udccdDelhi, India\n\nOur Address - G M Dance Centre.\nE-1A, Rajan Babu Rd, near Gali no 11, Majlis Park, Adarsh Nagar, Delhi, 110033\n\nManaged By Qyuki Digital Media.",
                "customUrl": "@gmdancecentre",
                "publishedAt": "2015-12-06T09:59:09Z",
                "thumbnails": {
                    "default": {
                        "url": "https://yt3.ggpht.com/ytc/AIdro_k1AsW1nFo7UP7jSJy1SppgcrwGmNN-RAo0NGT4I5xaAWU=s88-c-k-c0x00ffffff-no-rj",
                        "width": 88,
                        "height": 88
                    },
                    "medium": {
                        "url": "https://yt3.ggpht.com/ytc/AIdro_k1AsW1nFo7UP7jSJy1SppgcrwGmNN-RAo0NGT4I5xaAWU=s240-c-k-c0x00ffffff-no-rj",
                        "width": 240,
                        "height": 240
                    },
                    "high": {
                        "url": "https://yt3.ggpht.com/ytc/AIdro_k1AsW1nFo7UP7jSJy1SppgcrwGmNN-RAo0NGT4I5xaAWU=s800-c-k-c0x00ffffff-no-rj",
                        "width": 800,
                        "height": 800
                    }
                },
                "localized": {
                    "title": "G M Dance Centre",
                    "description": "Hi, Welcome to our Channel. \nWe will be uploading Dance Videos/Tutorials of different dance styles for all age groups. \nSubscribe to our channel to get the latest updates.\n\nFor business inquiry \nMail: gmdcindia@gmail.com \nWhatsapp +91-9990029978\n.\n\ud83d\udccdDelhi, India\n\nOur Address - G M Dance Centre.\nE-1A, Rajan Babu Rd, near Gali no 11, Majlis Park, Adarsh Nagar, Delhi, 110033\n\nManaged By Qyuki Digital Media."
                },
                "country": "IN"
            }
        }
    ]
}

In [92]:
request=yt.channels().list(
    id=ch_test_id,
    part=['contentDetails','snippet','statistics']
)

In [93]:
response=request.execute()

In [94]:
text=json.dumps(response,indent=4)
print(text)

{
    "kind": "youtube#channelListResponse",
    "etag": "DCEAk0XOHKqafAD1hExYxjQoMKg",
    "pageInfo": {
        "totalResults": 1,
        "resultsPerPage": 5
    },
    "items": [
        {
            "kind": "youtube#channel",
            "etag": "Ardphe3Hlxhp8tUF0V2QGbRjwbI",
            "id": "UCPbUTEjdU04ChIZfi53jczw",
            "snippet": {
                "title": "G M Dance Centre",
                "description": "Hi, Welcome to our Channel. \nWe will be uploading Dance Videos/Tutorials of different dance styles for all age groups. \nSubscribe to our channel to get the latest updates.\n\nFor business inquiry \nMail: gmdcindia@gmail.com \nWhatsapp +91-9990029978\n.\n\ud83d\udccdDelhi, India\n\nOur Address - G M Dance Centre.\nE-1A, Rajan Babu Rd, near Gali no 11, Majlis Park, Adarsh Nagar, Delhi, 110033\n\nManaged By Qyuki Digital Media.",
                "customUrl": "@gmdancecentre",
                "publishedAt": "2015-12-06T09:59:09Z",
                "thumbnails": {
                    "default": {
                        "url": "https://yt3.ggpht.com/ytc/AIdro_k1AsW1nFo7UP7jSJy1SppgcrwGmNN-RAo0NGT4I5xaAWU=s88-c-k-c0x00ffffff-no-rj",
                        "width": 88,
                        "height": 88
                    },
                    "medium": {
                        "url": "https://yt3.ggpht.com/ytc/AIdro_k1AsW1nFo7UP7jSJy1SppgcrwGmNN-RAo0NGT4I5xaAWU=s240-c-k-c0x00ffffff-no-rj",
                        "width": 240,
                        "height": 240
                    },
                    "high": {
                        "url": "https://yt3.ggpht.com/ytc/AIdro_k1AsW1nFo7UP7jSJy1SppgcrwGmNN-RAo0NGT4I5xaAWU=s800-c-k-c0x00ffffff-no-rj",
                        "width": 800,
                        "height": 800
                    }
                },
                "localized": {
                    "title": "G M Dance Centre",
                    "description": "Hi, Welcome to our Channel. \nWe will be uploading Dance Videos/Tutorials of different dance styles for all age groups. \nSubscribe to our channel to get the latest updates.\n\nFor business inquiry \nMail: gmdcindia@gmail.com \nWhatsapp +91-9990029978\n.\n\ud83d\udccdDelhi, India\n\nOur Address - G M Dance Centre.\nE-1A, Rajan Babu Rd, near Gali no 11, Majlis Park, Adarsh Nagar, Delhi, 110033\n\nManaged By Qyuki Digital Media."
                },
                "country": "IN"
            },
            "contentDetails": {
                "relatedPlaylists": {
                    "likes": "",
                    "uploads": "UUPbUTEjdU04ChIZfi53jczw"
                }
            },
            "statistics": {
                "viewCount": "2381954532",
                "subscriberCount": "6440000",
                "hiddenSubscriberCount": false,
                "videoCount": "404"
            }
        }
    ]
}

In [80]:
channel_name=response['items'][0]['snippet']['title']
channel_desc=response['items'][0]['snippet']['description']
channel_thumbnail=response['items'][0]['snippet']['thumbnails']['medium']['url']

In [81]:
uploads_id=response['items'][0]['contentDetails']['relatedPlaylists']['uploads']

In [82]:
subscibers=response['items'][0]['statistics']['subscriberCount']
total_videos=response['items'][0]['statistics']['videoCount']

# Fetching uploads playlist details

In [83]:
request=yt.playlistItems().list(
    playlistId=uploads_id,
    part=['contentDetails'],
    maxResults=5
)

In [84]:
response=request.execute()

In [85]:
text=json.dumps(response,indent=4)
print(text)

{
    "kind": "youtube#playlistItemListResponse",
    "etag": "t5-wxTpjEKMsn9tVoNdSkGmIJhk",
    "nextPageToken": "EAAaHlBUOkNBVWlFRVU0TURGQk1VWXhOVVEwTmtFNFJEQQ",
    "items": [
        {
            "kind": "youtube#playlistItem",
            "etag": "Xvnus08D-xK9ZfzfWKB-hOsE_dg",
            "id": "VVVYRW5zNzVFeHNFd3Z3NlVObU9RY05RLkllRFA1TUpmRlo0",
            "contentDetails": {
                "videoId": "IeDP5MJfFZ4",
                "videoPublishedAt": "2025-06-30T16:03:18Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "BsoKLOXxzOZMqgLlpU3B4TMDVzA",
            "id": "VVVYRW5zNzVFeHNFd3Z3NlVObU9RY05RLmVESGtOa3pTTkFj",
            "contentDetails": {
                "videoId": "eDHkNkzSNAc",
                "videoPublishedAt": "2025-06-27T18:38:28Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "nC3OAErerd6OsNl80bqZJSs6YgU",
            "id": "VVVYRW5zNzVFeHNFd3Z3NlVObU9RY05RLkQwQUtHUjhzT1NN",
            "contentDetails": {
                "videoId": "D0AKGR8sOSM",
                "videoPublishedAt": "2025-06-20T20:51:14Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "iU0Zoh7h2_aQ9AtZeEJXGWf28WY",
            "id": "VVVYRW5zNzVFeHNFd3Z3NlVObU9RY05RLlZlR2FXclJ2OXVz",
            "contentDetails": {
                "videoId": "VeGaWrRv9us",
                "videoPublishedAt": "2025-06-16T12:01:01Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "zDd1QK99z-wmPT3mUs3ufixayrk",
            "id": "VVVYRW5zNzVFeHNFd3Z3NlVObU9RY05RLjVmTkstUjZfOWxr",
            "contentDetails": {
                "videoId": "5fNK-R6_9lk",
                "videoPublishedAt": "2025-06-13T18:53:15Z"
            }
        }
    ],
    "pageInfo": {
        "totalResults": 72,
        "resultsPerPage": 5
    }
}

In [47]:
request=yt.playlistItems().list(
    playlistId=uploads_id,
    part=['contentDetails'],
    maxResults=5
    #pageToken="EAAaHlBUOkNBVWlFREUzUmpaQ05VRTRRall6TkRrNVF6aw"
)

In [48]:
response=request.execute()

In [49]:
text=json.dumps(response,indent=4)
print(text)

{
    "kind": "youtube#playlistItemListResponse",
    "etag": "o2w95tEEJtjl23G7AY5ex1vb06M",
    "nextPageToken": "EAAaHlBUOkNBVWlFRGc1T0RVMk1rUkNNVGN3TVRVME9UWQ",
    "items": [
        {
            "kind": "youtube#playlistItem",
            "etag": "NVvO2F9EE7CNuV2lx7e05H0JMTM",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLnZ6R2tTbjU5ckRV",
            "contentDetails": {
                "videoId": "vzGkSn59rDU",
                "videoPublishedAt": "2025-06-24T14:01:29Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "E70JTnRXt51pMBJ5Af9VYmiaL-c",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkFkT0RzUWRHSHow",
            "contentDetails": {
                "videoId": "AdODsQdGHz0",
                "videoPublishedAt": "2025-06-17T14:00:30Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "UAAnH9T5iglfUXY0dU_smsTQE-I",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLnVEVWZaeU5YRlgw",
            "contentDetails": {
                "videoId": "uDUfZyNXFX0",
                "videoPublishedAt": "2025-06-10T14:01:22Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "t0ILU_gFwCxf7hX7S917dz2Aj2c",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLmdjcXAzRmJ2NF9v",
            "contentDetails": {
                "videoId": "gcqp3Fbv4_o",
                "videoPublishedAt": "2025-06-03T14:01:08Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "XuRcSMlHrkGhXNUTrQfk7WVLdyw",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkxVSnc5ZVRVVFlR",
            "contentDetails": {
                "videoId": "LUJw9eTUTYQ",
                "videoPublishedAt": "2025-02-01T14:00:19Z"
            }
        }
    ],
    "pageInfo": {
        "totalResults": 77,
        "resultsPerPage": 5
    }
}

In [50]:
request=yt.playlistItems().list(
    playlistId=uploads_id,
    part=['contentDetails'],
    maxResults=50,
)

In [51]:
response=request.execute()

In [52]:
text=json.dumps(response,indent=4)
print(text)

{
    "kind": "youtube#playlistItemListResponse",
    "etag": "FAnIa6iY4VktfoZfv6Vv9x2yCZI",
    "nextPageToken": "EAAaHlBUOkNESWlFRGhHTURVelJqaEdOREEwUVRNd1FqWQ",
    "items": [
        {
            "kind": "youtube#playlistItem",
            "etag": "NVvO2F9EE7CNuV2lx7e05H0JMTM",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLnZ6R2tTbjU5ckRV",
            "contentDetails": {
                "videoId": "vzGkSn59rDU",
                "videoPublishedAt": "2025-06-24T14:01:29Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "E70JTnRXt51pMBJ5Af9VYmiaL-c",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkFkT0RzUWRHSHow",
            "contentDetails": {
                "videoId": "AdODsQdGHz0",
                "videoPublishedAt": "2025-06-17T14:00:30Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "UAAnH9T5iglfUXY0dU_smsTQE-I",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLnVEVWZaeU5YRlgw",
            "contentDetails": {
                "videoId": "uDUfZyNXFX0",
                "videoPublishedAt": "2025-06-10T14:01:22Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "t0ILU_gFwCxf7hX7S917dz2Aj2c",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLmdjcXAzRmJ2NF9v",
            "contentDetails": {
                "videoId": "gcqp3Fbv4_o",
                "videoPublishedAt": "2025-06-03T14:01:08Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "XuRcSMlHrkGhXNUTrQfk7WVLdyw",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkxVSnc5ZVRVVFlR",
            "contentDetails": {
                "videoId": "LUJw9eTUTYQ",
                "videoPublishedAt": "2025-02-01T14:00:19Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "z5YlwG6kMTvtelKstIk5I8R47fM",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLlE0clhteFExQVVN",
            "contentDetails": {
                "videoId": "Q4rXmxQ1AUM",
                "videoPublishedAt": "2025-01-27T14:00:26Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "pnaVhjl9o8DLx0-GoYJbg2BAj7E",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLjhwMGt0cGpJcmxJ",
            "contentDetails": {
                "videoId": "8p0ktpjIrlI",
                "videoPublishedAt": "2024-10-21T14:00:13Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "ss37P9kuodEJeevZeqSpdorh8PQ",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLmxrSGtZQ2tPS2Nz",
            "contentDetails": {
                "videoId": "lkHkYCkOKcs",
                "videoPublishedAt": "2024-10-07T14:00:44Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "Dg4l_QxEpKQn-XVAfQioHJdCk3o",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLlc2OFZFRkhDc0xj",
            "contentDetails": {
                "videoId": "W68VEFHCsLc",
                "videoPublishedAt": "2024-07-22T15:00:27Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "2dP-6JJEHmroTPmkwak0iYA5Wx4",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLlF2NzZud2liaC00",
            "contentDetails": {
                "videoId": "Qv76nwibh-4",
                "videoPublishedAt": "2024-07-08T15:00:32Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "4qMexIzJK_zHWE9g407jdww9ugo",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLmxkRk9OQm8yQ1Iw",
            "contentDetails": {
                "videoId": "ldFONBo2CR0",
                "videoPublishedAt": "2024-06-12T15:00:54Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "G5CxIW3nUtYNc5BplBIvswyld1M",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLjJUSnhweU8zZWk0",
            "contentDetails": {
                "videoId": "2TJxpyO3ei4",
                "videoPublishedAt": "2024-04-17T15:00:02Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "rz1xvKt6YQ4A3mQqeU4wUERd28M",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLlNaTlJrR3FhWVRJ",
            "contentDetails": {
                "videoId": "SZNRkGqaYTI",
                "videoPublishedAt": "2024-04-08T15:00:21Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "NkRkoeMednxD3qXwm7g9mxFNUMg",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLnhTREJHZkZSQ2lV",
            "contentDetails": {
                "videoId": "xSDBGfFRCiU",
                "videoPublishedAt": "2024-04-01T14:00:40Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "9n6jMohml5tJIijfHyG5kMNnI_0",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkh4T2hlcWI2UW1R",
            "contentDetails": {
                "videoId": "HxOheqb6QmQ",
                "videoPublishedAt": "2024-01-15T14:00:11Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "jeZKDacs9_zvx2R-61ugKx_jOUA",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLk83TkRvN1FsQnpj",
            "contentDetails": {
                "videoId": "O7NDo7QlBzc",
                "videoPublishedAt": "2024-01-01T14:00:20Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "nY4mWyZzlyj5IF9kNxoXc25QJaY",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkxRNXh0c3A3Z1lv",
            "contentDetails": {
                "videoId": "LQ5xtsp7gYo",
                "videoPublishedAt": "2023-12-25T14:00:12Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "24mmBhWDQBZA-HSMKySri5j8J-0",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLmJyLUJvUXBaaFcw",
            "contentDetails": {
                "videoId": "br-BoQpZhW0",
                "videoPublishedAt": "2023-12-18T14:00:21Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "6-5MoOb_JcyuWWykxxoAbgU1KLg",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLjlCOUNkS0FOam5N",
            "contentDetails": {
                "videoId": "9B9CdKANjnM",
                "videoPublishedAt": "2023-12-11T14:00:06Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "U2KeBQg9tRKIb8Nm9JKrfF0Fmrg",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkQwRDRQYTIyaUcw",
            "contentDetails": {
                "videoId": "D0D4Pa22iG0",
                "videoPublishedAt": "2023-11-27T14:00:09Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "jAIoefTttk1Ee_UjHc-CPGPKuS8",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLnRjcUVVU05DbjhJ",
            "contentDetails": {
                "videoId": "tcqEUSNCn8I",
                "videoPublishedAt": "2023-11-20T14:00:40Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "_yMWe4bp3Hyn0Yxb7-3m9Qv79aA",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLlIzS2dEODZWUnpj",
            "contentDetails": {
                "videoId": "R3KgD86VRzc",
                "videoPublishedAt": "2023-10-23T14:00:18Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "gTjnING_4MKY3zIwHHZct487X7k",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkt6NklsREN5T1VZ",
            "contentDetails": {
                "videoId": "Kz6IlDCyOUY",
                "videoPublishedAt": "2023-10-16T14:00:11Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "u-XHWo36_VE6HXCAmrRU1vQXDUM",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLmt3a2FCcktfLUJz",
            "contentDetails": {
                "videoId": "kwkaBrK_-Bs",
                "videoPublishedAt": "2023-10-09T14:00:24Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "xztiyMUhi25Q-_W2rsbIjNTTwrk",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLlhxSWZXa1ZJM1VB",
            "contentDetails": {
                "videoId": "XqIfWkVI3UA",
                "videoPublishedAt": "2023-10-03T14:00:30Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "DIB10dFDfZt8f6IRGUNUSCXwbSU",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkxGQ1RGemNNUXVB",
            "contentDetails": {
                "videoId": "LFCTFzcMQuA",
                "videoPublishedAt": "2023-09-25T15:00:24Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "GATnrmwWRxXAnjIsg0KtsitSfM4",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLlhJZFE2Z08zQW5j",
            "contentDetails": {
                "videoId": "XIdQ6gO3Anc",
                "videoPublishedAt": "2023-09-18T15:00:19Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "nkvh1P6xO7mbS6J2R0UxSXMBn6M",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLmlXUzlvZ01QT0kw",
            "contentDetails": {
                "videoId": "iWS9ogMPOI0",
                "videoPublishedAt": "2023-09-11T15:00:37Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "LCtSmgtC61SP14zDY2NxyuovYig",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkJtdE1yNk5tejlr",
            "contentDetails": {
                "videoId": "BmtMr6Nmz9k",
                "videoPublishedAt": "2023-09-04T15:00:16Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "SHv48Cf0qKyqQ-3IGHUrsyiMYq4",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLnVnd21IX3h6a0NB",
            "contentDetails": {
                "videoId": "ugwmH_xzkCA",
                "videoPublishedAt": "2023-08-28T15:00:44Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "BIaEqkjyXHA-qBFICqRJ-Qn58_I",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLndic2JYZmt2NDdB",
            "contentDetails": {
                "videoId": "wbsbXfkv47A",
                "videoPublishedAt": "2023-08-21T15:00:44Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "rI4zyQYBc3N39dhZbWFjKgIK5Xg",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLjl1TWNONjZtZndF",
            "contentDetails": {
                "videoId": "9uMcN66mfwE",
                "videoPublishedAt": "2023-08-07T15:00:12Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "7RLHB5vHHSyf1BFxhkSDX9SkPds",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLnhpM0YyWnY5MVVF",
            "contentDetails": {
                "videoId": "xi3F2Zv91UE",
                "videoPublishedAt": "2023-08-01T12:30:35Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "DxuI4DAbFN_o185OAzdD9evrB8s",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkhURDg2aDY5UHRF",
            "contentDetails": {
                "videoId": "HTD86h69PtE",
                "videoPublishedAt": "2023-04-07T15:00:10Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "UznEdrz3Ap35k9guRvL9yBgimQY",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLjNWcC1hSEozZ0Jz",
            "contentDetails": {
                "videoId": "3Vp-aHJ3gBs",
                "videoPublishedAt": "2023-04-06T15:00:02Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "q9CrvJ8fm287EcrZBrhrLiNRWhI",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLlFoUE5LVng1MlBV",
            "contentDetails": {
                "videoId": "QhPNKVx52PU",
                "videoPublishedAt": "2023-04-05T15:00:15Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "20Emu8r_OP-wOsOIF1pY4Cie0_k",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLm9JZWpBSFdlNktn",
            "contentDetails": {
                "videoId": "oIejAHWe6Kg",
                "videoPublishedAt": "2023-04-04T15:00:34Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "IoWXQWU6SZKfSRnfCPjubODC0pQ",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLmNWV0h4aEJacXY4",
            "contentDetails": {
                "videoId": "cVWHxhBZqv8",
                "videoPublishedAt": "2023-04-03T15:00:23Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "Dq2Z4dmKscTfFXDekMcWHIlglb8",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLnU5eDFWWkRpZHRN",
            "contentDetails": {
                "videoId": "u9x1VZDidtM",
                "videoPublishedAt": "2023-04-02T15:00:38Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "v1BI5pXGyk5wVjmqu8ZEevctbtw",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLlpQU0VTX2d0bTVV",
            "contentDetails": {
                "videoId": "ZPSES_gtm5U",
                "videoPublishedAt": "2023-04-01T14:00:31Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "ChjAMXUbZ8W0hje9isCt2BBVd30",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLnZlNGVDNjhHMElv",
            "contentDetails": {
                "videoId": "ve4eC68G0Io",
                "videoPublishedAt": "2023-03-31T14:00:38Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "2mRDY4Oe6Y3a3EeUtTigpqtIzn0",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLi1yWlBNLVZsS0I4",
            "contentDetails": {
                "videoId": "-rZPM-VlKB8",
                "videoPublishedAt": "2023-03-30T14:00:00Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "kXhiERIKbPy9IbrVu-ce6roLW-0",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLmNxTzJTMktkUWM4",
            "contentDetails": {
                "videoId": "cqO2S2KdQc8",
                "videoPublishedAt": "2023-03-29T14:00:22Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "Jjp1OZIWkfRSgm75USAmCO0h42A",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLjFBZEZ0ekJTa3hz",
            "contentDetails": {
                "videoId": "1AdFtzBSkxs",
                "videoPublishedAt": "2023-03-28T14:00:01Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "GLBoHU6PxUkwOBpGumni3ZfJseU",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLk5mVHJGaGZxbUZZ",
            "contentDetails": {
                "videoId": "NfTrFhfqmFY",
                "videoPublishedAt": "2023-03-27T14:00:13Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "llhnTfGorty3St4ajb4sQB681gQ",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLktCbzdtWkhsaW5r",
            "contentDetails": {
                "videoId": "KBo7mZHlink",
                "videoPublishedAt": "2023-03-13T14:00:18Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "BURho1pK3JGx6uMilcdvM2ovWxg",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLm9fR0JGc3F1WnVJ",
            "contentDetails": {
                "videoId": "o_GBFsquZuI",
                "videoPublishedAt": "2023-02-01T15:03:46Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "Fk8y4W84SFA9b9yF1yBeq4tzGzQ",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLklyRFJIelQyNkY0",
            "contentDetails": {
                "videoId": "IrDRHzT26F4",
                "videoPublishedAt": "2023-01-23T16:00:07Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "n2G66GcMl4GRZ8SttUrwuNwCRzs",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLmMxdGdaWDJJR3F3",
            "contentDetails": {
                "videoId": "c1tgZX2IGqw",
                "videoPublishedAt": "2023-01-16T16:00:18Z"
            }
        },
        {
            "kind": "youtube#playlistItem",
            "etag": "D9t20UHvurfEKfJRCzT_0m04GMY",
            "id": "VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkVHX1Vxbk1WN1dr",
            "contentDetails": {
                "videoId": "EG_UqnMV7Wk",
                "videoPublishedAt": "2022-12-15T13:12:57Z"
            }
        }
    ],
    "pageInfo": {
        "totalResults": 77,
        "resultsPerPage": 50
    }
}

In [53]:
try:next_page=response['items'][0]['nextPageToken'] 
except: next_page='NA'

In [54]:
v_id=[]
for item in response['items']:
    v_id.append(item['contentDetails']['videoId'])

In [55]:
v_id

['vzGkSn59rDU',
 'AdODsQdGHz0',
 'uDUfZyNXFX0',
 'gcqp3Fbv4_o',
 'LUJw9eTUTYQ',
 'Q4rXmxQ1AUM',
 '8p0ktpjIrlI',
 'lkHkYCkOKcs',
 'W68VEFHCsLc',
 'Qv76nwibh-4',
 'ldFONBo2CR0',
 '2TJxpyO3ei4',
 'SZNRkGqaYTI',
 'xSDBGfFRCiU',
 'HxOheqb6QmQ',
 'O7NDo7QlBzc',
 'LQ5xtsp7gYo',
 'br-BoQpZhW0',
 '9B9CdKANjnM',
 'D0D4Pa22iG0',
 'tcqEUSNCn8I',
 'R3KgD86VRzc',
 'Kz6IlDCyOUY',
 'kwkaBrK_-Bs',
 'XqIfWkVI3UA',
 'LFCTFzcMQuA',
 'XIdQ6gO3Anc',
 'iWS9ogMPOI0',
 'BmtMr6Nmz9k',
 'ugwmH_xzkCA',
 'wbsbXfkv47A',
 '9uMcN66mfwE',
 'xi3F2Zv91UE',
 'HTD86h69PtE',
 '3Vp-aHJ3gBs',
 'QhPNKVx52PU',
 'oIejAHWe6Kg',
 'cVWHxhBZqv8',
 'u9x1VZDidtM',
 'ZPSES_gtm5U',
 've4eC68G0Io',
 '-rZPM-VlKB8',
 'cqO2S2KdQc8',
 '1AdFtzBSkxs',
 'NfTrFhfqmFY',
 'KBo7mZHlink',
 'o_GBFsquZuI',
 'IrDRHzT26F4',
 'c1tgZX2IGqw',
 'EG_UqnMV7Wk']

In [56]:
import pandas as pd

In [57]:
df=pd.DataFrame(response['items'][0])

In [58]:
df=pd.DataFrame(response['items'][0])
for item in response['items']:
    df2=pd.DataFrame(item)
    df=pd.concat([df,df2],ignore_index=True)

In [59]:
df

,kind,etag,id,contentDetails
0,youtube#playlistItem,NVvO2F9EE7CNuV2lx7e05H0JMTM,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLnZ6R2tTbjU5ckRV,vzGkSn59rDU
1,youtube#playlistItem,NVvO2F9EE7CNuV2lx7e05H0JMTM,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLnZ6R2tTbjU5ckRV,2025-06-24T14:01:29Z
2,youtube#playlistItem,NVvO2F9EE7CNuV2lx7e05H0JMTM,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLnZ6R2tTbjU5ckRV,vzGkSn59rDU
3,youtube#playlistItem,NVvO2F9EE7CNuV2lx7e05H0JMTM,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLnZ6R2tTbjU5ckRV,2025-06-24T14:01:29Z
4,youtube#playlistItem,E70JTnRXt51pMBJ5Af9VYmiaL-c,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkFkT0RzUWRHSHow,AdODsQdGHz0
...,...,...,...,...
97,youtube#playlistItem,Fk8y4W84SFA9b9yF1yBeq4tzGzQ,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLklyRFJIelQyNkY0,2023-01-23T16:00:07Z
98,youtube#playlistItem,n2G66GcMl4GRZ8SttUrwuNwCRzs,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLmMxdGdaWDJJR3F3,c1tgZX2IGqw
99,youtube#playlistItem,n2G66GcMl4GRZ8SttUrwuNwCRzs,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLmMxdGdaWDJJR3F3,2023-01-16T16:00:18Z
100,youtube#playlistItem,D9t20UHvurfEKfJRCzT_0m04GMY,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkVHX1Vxbk1WN1dr,EG_UqnMV7Wk
101,youtube#playlistItem,D9t20UHvurfEKfJRCzT_0m04GMY,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkVHX1Vxbk1WN1dr,2022-12-15T13:12:57Z

In [60]:
df.drop_duplicates(subset=['kind','etag','id'],inplace=True)

In [61]:
df.reset_index()

,index,kind,etag,id,contentDetails
0,0,youtube#playlistItem,NVvO2F9EE7CNuV2lx7e05H0JMTM,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLnZ6R2tTbjU5ckRV,vzGkSn59rDU
1,4,youtube#playlistItem,E70JTnRXt51pMBJ5Af9VYmiaL-c,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkFkT0RzUWRHSHow,AdODsQdGHz0
2,6,youtube#playlistItem,UAAnH9T5iglfUXY0dU_smsTQE-I,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLnVEVWZaeU5YRlgw,uDUfZyNXFX0
3,8,youtube#playlistItem,t0ILU_gFwCxf7hX7S917dz2Aj2c,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLmdjcXAzRmJ2NF9v,gcqp3Fbv4_o
4,10,youtube#playlistItem,XuRcSMlHrkGhXNUTrQfk7WVLdyw,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkxVSnc5ZVRVVFlR,LUJw9eTUTYQ
5,12,youtube#playlistItem,z5YlwG6kMTvtelKstIk5I8R47fM,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLlE0clhteFExQVVN,Q4rXmxQ1AUM
6,14,youtube#playlistItem,pnaVhjl9o8DLx0-GoYJbg2BAj7E,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLjhwMGt0cGpJcmxJ,8p0ktpjIrlI
7,16,youtube#playlistItem,ss37P9kuodEJeevZeqSpdorh8PQ,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLmxrSGtZQ2tPS2Nz,lkHkYCkOKcs
8,18,youtube#playlistItem,Dg4l_QxEpKQn-XVAfQioHJdCk3o,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLlc2OFZFRkhDc0xj,W68VEFHCsLc
9,20,youtube#playlistItem,2dP-6JJEHmroTPmkwak0iYA5Wx4,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLlF2NzZud2liaC00,Qv76nwibh-4
10,22,youtube#playlistItem,4qMexIzJK_zHWE9g407jdww9ugo,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLmxkRk9OQm8yQ1Iw,ldFONBo2CR0
11,24,youtube#playlistItem,G5CxIW3nUtYNc5BplBIvswyld1M,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLjJUSnhweU8zZWk0,2TJxpyO3ei4
12,26,youtube#playlistItem,rz1xvKt6YQ4A3mQqeU4wUERd28M,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLlNaTlJrR3FhWVRJ,SZNRkGqaYTI
13,28,youtube#playlistItem,NkRkoeMednxD3qXwm7g9mxFNUMg,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLnhTREJHZkZSQ2lV,xSDBGfFRCiU
14,30,youtube#playlistItem,9n6jMohml5tJIijfHyG5kMNnI_0,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkh4T2hlcWI2UW1R,HxOheqb6QmQ
15,32,youtube#playlistItem,jeZKDacs9_zvx2R-61ugKx_jOUA,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLk83TkRvN1FsQnpj,O7NDo7QlBzc
16,34,youtube#playlistItem,nY4mWyZzlyj5IF9kNxoXc25QJaY,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkxRNXh0c3A3Z1lv,LQ5xtsp7gYo
17,36,youtube#playlistItem,24mmBhWDQBZA-HSMKySri5j8J-0,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLmJyLUJvUXBaaFcw,br-BoQpZhW0
18,38,youtube#playlistItem,6-5MoOb_JcyuWWykxxoAbgU1KLg,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLjlCOUNkS0FOam5N,9B9CdKANjnM
19,40,youtube#playlistItem,U2KeBQg9tRKIb8Nm9JKrfF0Fmrg,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkQwRDRQYTIyaUcw,D0D4Pa22iG0
20,42,youtube#playlistItem,jAIoefTttk1Ee_UjHc-CPGPKuS8,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLnRjcUVVU05DbjhJ,tcqEUSNCn8I
21,44,youtube#playlistItem,_yMWe4bp3Hyn0Yxb7-3m9Qv79aA,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLlIzS2dEODZWUnpj,R3KgD86VRzc
22,46,youtube#playlistItem,gTjnING_4MKY3zIwHHZct487X7k,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkt6NklsREN5T1VZ,Kz6IlDCyOUY
23,48,youtube#playlistItem,u-XHWo36_VE6HXCAmrRU1vQXDUM,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLmt3a2FCcktfLUJz,kwkaBrK_-Bs
24,50,youtube#playlistItem,xztiyMUhi25Q-_W2rsbIjNTTwrk,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLlhxSWZXa1ZJM1VB,XqIfWkVI3UA
25,52,youtube#playlistItem,DIB10dFDfZt8f6IRGUNUSCXwbSU,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkxGQ1RGemNNUXVB,LFCTFzcMQuA
26,54,youtube#playlistItem,GATnrmwWRxXAnjIsg0KtsitSfM4,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLlhJZFE2Z08zQW5j,XIdQ6gO3Anc
27,56,youtube#playlistItem,nkvh1P6xO7mbS6J2R0UxSXMBn6M,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLmlXUzlvZ01QT0kw,iWS9ogMPOI0
28,58,youtube#playlistItem,LCtSmgtC61SP14zDY2NxyuovYig,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkJtdE1yNk5tejlr,BmtMr6Nmz9k
29,60,youtube#playlistItem,SHv48Cf0qKyqQ-3IGHUrsyiMYq4,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLnVnd21IX3h6a0NB,ugwmH_xzkCA
30,62,youtube#playlistItem,BIaEqkjyXHA-qBFICqRJ-Qn58_I,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLndic2JYZmt2NDdB,wbsbXfkv47A
31,64,youtube#playlistItem,rI4zyQYBc3N39dhZbWFjKgIK5Xg,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLjl1TWNONjZtZndF,9uMcN66mfwE
32,66,youtube#playlistItem,7RLHB5vHHSyf1BFxhkSDX9SkPds,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLnhpM0YyWnY5MVVF,xi3F2Zv91UE
33,68,youtube#playlistItem,DxuI4DAbFN_o185OAzdD9evrB8s,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkhURDg2aDY5UHRF,HTD86h69PtE
34,70,youtube#playlistItem,UznEdrz3Ap35k9guRvL9yBgimQY,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLjNWcC1hSEozZ0Jz,3Vp-aHJ3gBs
35,72,youtube#playlistItem,q9CrvJ8fm287EcrZBrhrLiNRWhI,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLlFoUE5LVng1MlBV,QhPNKVx52PU
36,74,youtube#playlistItem,20Emu8r_OP-wOsOIF1pY4Cie0_k,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLm9JZWpBSFdlNktn,oIejAHWe6Kg
37,76,youtube#playlistItem,IoWXQWU6SZKfSRnfCPjubODC0pQ,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLmNWV0h4aEJacXY4,cVWHxhBZqv8
38,78,youtube#playlistItem,Dq2Z4dmKscTfFXDekMcWHIlglb8,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLnU5eDFWWkRpZHRN,u9x1VZDidtM
39,80,youtube#playlistItem,v1BI5pXGyk5wVjmqu8ZEevctbtw,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLlpQU0VTX2d0bTVV,ZPSES_gtm5U
40,82,youtube#playlistItem,ChjAMXUbZ8W0hje9isCt2BBVd30,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLnZlNGVDNjhHMElv,ve4eC68G0Io
41,84,youtube#playlistItem,2mRDY4Oe6Y3a3EeUtTigpqtIzn0,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLi1yWlBNLVZsS0I4,-rZPM-VlKB8
42,86,youtube#playlistItem,kXhiERIKbPy9IbrVu-ce6roLW-0,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLmNxTzJTMktkUWM4,cqO2S2KdQc8
43,88,youtube#playlistItem,Jjp1OZIWkfRSgm75USAmCO0h42A,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLjFBZEZ0ekJTa3hz,1AdFtzBSkxs
44,90,youtube#playlistItem,GLBoHU6PxUkwOBpGumni3ZfJseU,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLk5mVHJGaGZxbUZZ,NfTrFhfqmFY
45,92,youtube#playlistItem,llhnTfGorty3St4ajb4sQB681gQ,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLktCbzdtWkhsaW5r,KBo7mZHlink
46,94,youtube#playlistItem,BURho1pK3JGx6uMilcdvM2ovWxg,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLm9fR0JGc3F1WnVJ,o_GBFsquZuI
47,96,youtube#playlistItem,Fk8y4W84SFA9b9yF1yBeq4tzGzQ,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLklyRFJIelQyNkY0,IrDRHzT26F4
48,98,youtube#playlistItem,n2G66GcMl4GRZ8SttUrwuNwCRzs,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLmMxdGdaWDJJR3F3,c1tgZX2IGqw
49,100,youtube#playlistItem,D9t20UHvurfEKfJRCzT_0m04GMY,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkVHX1Vxbk1WN1dr,EG_UqnMV7Wk

In [62]:
import numpy as np
df.index=np.linspace(1,50,50).astype(int)

In [63]:
df

,kind,etag,id,contentDetails
1,youtube#playlistItem,NVvO2F9EE7CNuV2lx7e05H0JMTM,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLnZ6R2tTbjU5ckRV,vzGkSn59rDU
2,youtube#playlistItem,E70JTnRXt51pMBJ5Af9VYmiaL-c,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkFkT0RzUWRHSHow,AdODsQdGHz0
3,youtube#playlistItem,UAAnH9T5iglfUXY0dU_smsTQE-I,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLnVEVWZaeU5YRlgw,uDUfZyNXFX0
4,youtube#playlistItem,t0ILU_gFwCxf7hX7S917dz2Aj2c,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLmdjcXAzRmJ2NF9v,gcqp3Fbv4_o
5,youtube#playlistItem,XuRcSMlHrkGhXNUTrQfk7WVLdyw,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkxVSnc5ZVRVVFlR,LUJw9eTUTYQ
6,youtube#playlistItem,z5YlwG6kMTvtelKstIk5I8R47fM,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLlE0clhteFExQVVN,Q4rXmxQ1AUM
7,youtube#playlistItem,pnaVhjl9o8DLx0-GoYJbg2BAj7E,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLjhwMGt0cGpJcmxJ,8p0ktpjIrlI
8,youtube#playlistItem,ss37P9kuodEJeevZeqSpdorh8PQ,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLmxrSGtZQ2tPS2Nz,lkHkYCkOKcs
9,youtube#playlistItem,Dg4l_QxEpKQn-XVAfQioHJdCk3o,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLlc2OFZFRkhDc0xj,W68VEFHCsLc
10,youtube#playlistItem,2dP-6JJEHmroTPmkwak0iYA5Wx4,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLlF2NzZud2liaC00,Qv76nwibh-4
11,youtube#playlistItem,4qMexIzJK_zHWE9g407jdww9ugo,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLmxkRk9OQm8yQ1Iw,ldFONBo2CR0
12,youtube#playlistItem,G5CxIW3nUtYNc5BplBIvswyld1M,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLjJUSnhweU8zZWk0,2TJxpyO3ei4
13,youtube#playlistItem,rz1xvKt6YQ4A3mQqeU4wUERd28M,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLlNaTlJrR3FhWVRJ,SZNRkGqaYTI
14,youtube#playlistItem,NkRkoeMednxD3qXwm7g9mxFNUMg,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLnhTREJHZkZSQ2lV,xSDBGfFRCiU
15,youtube#playlistItem,9n6jMohml5tJIijfHyG5kMNnI_0,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkh4T2hlcWI2UW1R,HxOheqb6QmQ
16,youtube#playlistItem,jeZKDacs9_zvx2R-61ugKx_jOUA,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLk83TkRvN1FsQnpj,O7NDo7QlBzc
17,youtube#playlistItem,nY4mWyZzlyj5IF9kNxoXc25QJaY,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkxRNXh0c3A3Z1lv,LQ5xtsp7gYo
18,youtube#playlistItem,24mmBhWDQBZA-HSMKySri5j8J-0,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLmJyLUJvUXBaaFcw,br-BoQpZhW0
19,youtube#playlistItem,6-5MoOb_JcyuWWykxxoAbgU1KLg,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLjlCOUNkS0FOam5N,9B9CdKANjnM
20,youtube#playlistItem,U2KeBQg9tRKIb8Nm9JKrfF0Fmrg,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkQwRDRQYTIyaUcw,D0D4Pa22iG0
21,youtube#playlistItem,jAIoefTttk1Ee_UjHc-CPGPKuS8,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLnRjcUVVU05DbjhJ,tcqEUSNCn8I
22,youtube#playlistItem,_yMWe4bp3Hyn0Yxb7-3m9Qv79aA,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLlIzS2dEODZWUnpj,R3KgD86VRzc
23,youtube#playlistItem,gTjnING_4MKY3zIwHHZct487X7k,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkt6NklsREN5T1VZ,Kz6IlDCyOUY
24,youtube#playlistItem,u-XHWo36_VE6HXCAmrRU1vQXDUM,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLmt3a2FCcktfLUJz,kwkaBrK_-Bs
25,youtube#playlistItem,xztiyMUhi25Q-_W2rsbIjNTTwrk,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLlhxSWZXa1ZJM1VB,XqIfWkVI3UA
26,youtube#playlistItem,DIB10dFDfZt8f6IRGUNUSCXwbSU,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkxGQ1RGemNNUXVB,LFCTFzcMQuA
27,youtube#playlistItem,GATnrmwWRxXAnjIsg0KtsitSfM4,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLlhJZFE2Z08zQW5j,XIdQ6gO3Anc
28,youtube#playlistItem,nkvh1P6xO7mbS6J2R0UxSXMBn6M,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLmlXUzlvZ01QT0kw,iWS9ogMPOI0
29,youtube#playlistItem,LCtSmgtC61SP14zDY2NxyuovYig,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkJtdE1yNk5tejlr,BmtMr6Nmz9k
30,youtube#playlistItem,SHv48Cf0qKyqQ-3IGHUrsyiMYq4,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLnVnd21IX3h6a0NB,ugwmH_xzkCA
31,youtube#playlistItem,BIaEqkjyXHA-qBFICqRJ-Qn58_I,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLndic2JYZmt2NDdB,wbsbXfkv47A
32,youtube#playlistItem,rI4zyQYBc3N39dhZbWFjKgIK5Xg,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLjl1TWNONjZtZndF,9uMcN66mfwE
33,youtube#playlistItem,7RLHB5vHHSyf1BFxhkSDX9SkPds,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLnhpM0YyWnY5MVVF,xi3F2Zv91UE
34,youtube#playlistItem,DxuI4DAbFN_o185OAzdD9evrB8s,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkhURDg2aDY5UHRF,HTD86h69PtE
35,youtube#playlistItem,UznEdrz3Ap35k9guRvL9yBgimQY,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLjNWcC1hSEozZ0Jz,3Vp-aHJ3gBs
36,youtube#playlistItem,q9CrvJ8fm287EcrZBrhrLiNRWhI,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLlFoUE5LVng1MlBV,QhPNKVx52PU
37,youtube#playlistItem,20Emu8r_OP-wOsOIF1pY4Cie0_k,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLm9JZWpBSFdlNktn,oIejAHWe6Kg
38,youtube#playlistItem,IoWXQWU6SZKfSRnfCPjubODC0pQ,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLmNWV0h4aEJacXY4,cVWHxhBZqv8
39,youtube#playlistItem,Dq2Z4dmKscTfFXDekMcWHIlglb8,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLnU5eDFWWkRpZHRN,u9x1VZDidtM
40,youtube#playlistItem,v1BI5pXGyk5wVjmqu8ZEevctbtw,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLlpQU0VTX2d0bTVV,ZPSES_gtm5U
41,youtube#playlistItem,ChjAMXUbZ8W0hje9isCt2BBVd30,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLnZlNGVDNjhHMElv,ve4eC68G0Io
42,youtube#playlistItem,2mRDY4Oe6Y3a3EeUtTigpqtIzn0,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLi1yWlBNLVZsS0I4,-rZPM-VlKB8
43,youtube#playlistItem,kXhiERIKbPy9IbrVu-ce6roLW-0,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLmNxTzJTMktkUWM4,cqO2S2KdQc8
44,youtube#playlistItem,Jjp1OZIWkfRSgm75USAmCO0h42A,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLjFBZEZ0ekJTa3hz,1AdFtzBSkxs
45,youtube#playlistItem,GLBoHU6PxUkwOBpGumni3ZfJseU,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLk5mVHJGaGZxbUZZ,NfTrFhfqmFY
46,youtube#playlistItem,llhnTfGorty3St4ajb4sQB681gQ,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLktCbzdtWkhsaW5r,KBo7mZHlink
47,youtube#playlistItem,BURho1pK3JGx6uMilcdvM2ovWxg,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLm9fR0JGc3F1WnVJ,o_GBFsquZuI
48,youtube#playlistItem,Fk8y4W84SFA9b9yF1yBeq4tzGzQ,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLklyRFJIelQyNkY0,IrDRHzT26F4
49,youtube#playlistItem,n2G66GcMl4GRZ8SttUrwuNwCRzs,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLmMxdGdaWDJJR3F3,c1tgZX2IGqw
50,youtube#playlistItem,D9t20UHvurfEKfJRCzT_0m04GMY,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkVHX1Vxbk1WN1dr,EG_UqnMV7Wk

In [65]:
df

,kind,etag,id,contentDetails
1,youtube#playlistItem,NVvO2F9EE7CNuV2lx7e05H0JMTM,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLnZ6R2tTbjU5ckRV,vzGkSn59rDU
2,youtube#playlistItem,E70JTnRXt51pMBJ5Af9VYmiaL-c,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkFkT0RzUWRHSHow,AdODsQdGHz0
3,youtube#playlistItem,UAAnH9T5iglfUXY0dU_smsTQE-I,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLnVEVWZaeU5YRlgw,uDUfZyNXFX0
4,youtube#playlistItem,t0ILU_gFwCxf7hX7S917dz2Aj2c,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLmdjcXAzRmJ2NF9v,gcqp3Fbv4_o
5,youtube#playlistItem,XuRcSMlHrkGhXNUTrQfk7WVLdyw,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkxVSnc5ZVRVVFlR,LUJw9eTUTYQ
6,youtube#playlistItem,z5YlwG6kMTvtelKstIk5I8R47fM,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLlE0clhteFExQVVN,Q4rXmxQ1AUM
7,youtube#playlistItem,pnaVhjl9o8DLx0-GoYJbg2BAj7E,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLjhwMGt0cGpJcmxJ,8p0ktpjIrlI
8,youtube#playlistItem,ss37P9kuodEJeevZeqSpdorh8PQ,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLmxrSGtZQ2tPS2Nz,lkHkYCkOKcs
9,youtube#playlistItem,Dg4l_QxEpKQn-XVAfQioHJdCk3o,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLlc2OFZFRkhDc0xj,W68VEFHCsLc
10,youtube#playlistItem,2dP-6JJEHmroTPmkwak0iYA5Wx4,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLlF2NzZud2liaC00,Qv76nwibh-4
11,youtube#playlistItem,4qMexIzJK_zHWE9g407jdww9ugo,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLmxkRk9OQm8yQ1Iw,ldFONBo2CR0
12,youtube#playlistItem,G5CxIW3nUtYNc5BplBIvswyld1M,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLjJUSnhweU8zZWk0,2TJxpyO3ei4
13,youtube#playlistItem,rz1xvKt6YQ4A3mQqeU4wUERd28M,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLlNaTlJrR3FhWVRJ,SZNRkGqaYTI
14,youtube#playlistItem,NkRkoeMednxD3qXwm7g9mxFNUMg,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLnhTREJHZkZSQ2lV,xSDBGfFRCiU
15,youtube#playlistItem,9n6jMohml5tJIijfHyG5kMNnI_0,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkh4T2hlcWI2UW1R,HxOheqb6QmQ
16,youtube#playlistItem,jeZKDacs9_zvx2R-61ugKx_jOUA,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLk83TkRvN1FsQnpj,O7NDo7QlBzc
17,youtube#playlistItem,nY4mWyZzlyj5IF9kNxoXc25QJaY,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkxRNXh0c3A3Z1lv,LQ5xtsp7gYo
18,youtube#playlistItem,24mmBhWDQBZA-HSMKySri5j8J-0,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLmJyLUJvUXBaaFcw,br-BoQpZhW0
19,youtube#playlistItem,6-5MoOb_JcyuWWykxxoAbgU1KLg,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLjlCOUNkS0FOam5N,9B9CdKANjnM
20,youtube#playlistItem,U2KeBQg9tRKIb8Nm9JKrfF0Fmrg,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkQwRDRQYTIyaUcw,D0D4Pa22iG0
21,youtube#playlistItem,jAIoefTttk1Ee_UjHc-CPGPKuS8,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLnRjcUVVU05DbjhJ,tcqEUSNCn8I
22,youtube#playlistItem,_yMWe4bp3Hyn0Yxb7-3m9Qv79aA,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLlIzS2dEODZWUnpj,R3KgD86VRzc
23,youtube#playlistItem,gTjnING_4MKY3zIwHHZct487X7k,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkt6NklsREN5T1VZ,Kz6IlDCyOUY
24,youtube#playlistItem,u-XHWo36_VE6HXCAmrRU1vQXDUM,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLmt3a2FCcktfLUJz,kwkaBrK_-Bs
25,youtube#playlistItem,xztiyMUhi25Q-_W2rsbIjNTTwrk,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLlhxSWZXa1ZJM1VB,XqIfWkVI3UA
26,youtube#playlistItem,DIB10dFDfZt8f6IRGUNUSCXwbSU,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkxGQ1RGemNNUXVB,LFCTFzcMQuA
27,youtube#playlistItem,GATnrmwWRxXAnjIsg0KtsitSfM4,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLlhJZFE2Z08zQW5j,XIdQ6gO3Anc
28,youtube#playlistItem,nkvh1P6xO7mbS6J2R0UxSXMBn6M,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLmlXUzlvZ01QT0kw,iWS9ogMPOI0
29,youtube#playlistItem,LCtSmgtC61SP14zDY2NxyuovYig,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkJtdE1yNk5tejlr,BmtMr6Nmz9k
30,youtube#playlistItem,SHv48Cf0qKyqQ-3IGHUrsyiMYq4,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLnVnd21IX3h6a0NB,ugwmH_xzkCA
31,youtube#playlistItem,BIaEqkjyXHA-qBFICqRJ-Qn58_I,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLndic2JYZmt2NDdB,wbsbXfkv47A
32,youtube#playlistItem,rI4zyQYBc3N39dhZbWFjKgIK5Xg,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLjl1TWNONjZtZndF,9uMcN66mfwE
33,youtube#playlistItem,7RLHB5vHHSyf1BFxhkSDX9SkPds,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLnhpM0YyWnY5MVVF,xi3F2Zv91UE
34,youtube#playlistItem,DxuI4DAbFN_o185OAzdD9evrB8s,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkhURDg2aDY5UHRF,HTD86h69PtE
35,youtube#playlistItem,UznEdrz3Ap35k9guRvL9yBgimQY,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLjNWcC1hSEozZ0Jz,3Vp-aHJ3gBs
36,youtube#playlistItem,q9CrvJ8fm287EcrZBrhrLiNRWhI,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLlFoUE5LVng1MlBV,QhPNKVx52PU
37,youtube#playlistItem,20Emu8r_OP-wOsOIF1pY4Cie0_k,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLm9JZWpBSFdlNktn,oIejAHWe6Kg
38,youtube#playlistItem,IoWXQWU6SZKfSRnfCPjubODC0pQ,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLmNWV0h4aEJacXY4,cVWHxhBZqv8
39,youtube#playlistItem,Dq2Z4dmKscTfFXDekMcWHIlglb8,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLnU5eDFWWkRpZHRN,u9x1VZDidtM
40,youtube#playlistItem,v1BI5pXGyk5wVjmqu8ZEevctbtw,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLlpQU0VTX2d0bTVV,ZPSES_gtm5U
41,youtube#playlistItem,ChjAMXUbZ8W0hje9isCt2BBVd30,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLnZlNGVDNjhHMElv,ve4eC68G0Io
42,youtube#playlistItem,2mRDY4Oe6Y3a3EeUtTigpqtIzn0,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLi1yWlBNLVZsS0I4,-rZPM-VlKB8
43,youtube#playlistItem,kXhiERIKbPy9IbrVu-ce6roLW-0,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLmNxTzJTMktkUWM4,cqO2S2KdQc8
44,youtube#playlistItem,Jjp1OZIWkfRSgm75USAmCO0h42A,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLjFBZEZ0ekJTa3hz,1AdFtzBSkxs
45,youtube#playlistItem,GLBoHU6PxUkwOBpGumni3ZfJseU,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLk5mVHJGaGZxbUZZ,NfTrFhfqmFY
46,youtube#playlistItem,llhnTfGorty3St4ajb4sQB681gQ,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLktCbzdtWkhsaW5r,KBo7mZHlink
47,youtube#playlistItem,BURho1pK3JGx6uMilcdvM2ovWxg,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLm9fR0JGc3F1WnVJ,o_GBFsquZuI
48,youtube#playlistItem,Fk8y4W84SFA9b9yF1yBeq4tzGzQ,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLklyRFJIelQyNkY0,IrDRHzT26F4
49,youtube#playlistItem,n2G66GcMl4GRZ8SttUrwuNwCRzs,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLmMxdGdaWDJJR3F3,c1tgZX2IGqw
50,youtube#playlistItem,D9t20UHvurfEKfJRCzT_0m04GMY,VVV1eGhUU0t0bk1KaXppbmJsTHM5eE9BLkVHX1Vxbk1WN1dr,EG_UqnMV7Wk

In [66]:
video_ids = df['contentDetails'].tolist()

In [67]:
request=yt.videos().list(
    id=','.join(video_ids),
    part='statistics,contentDetails,snippet'
)

In [68]:
print()

In [69]:
response=request.execute()

In [70]:
text=json.dumps(response,indent=4)
print(text)

{
    "kind": "youtube#videoListResponse",
    "etag": "A35BUEPi97AQeob-f9kJ_y2ZMJs",
    "items": [
        {
            "kind": "youtube#video",
            "etag": "SpNlM1_gS4r_YD7UamBDP48z07c",
            "id": "vzGkSn59rDU",
            "snippet": {
                "publishedAt": "2025-06-24T14:01:29Z",
                "channelId": "UCuxhTSKtnMJizinblLs9xOA",
                "title": "Build an MCP Server in 20 Minutes (with Python)",
                "description": "Learn how to build an MCP server in Python and connect it to Claude Desktop and use it as an AI agent. This MCP server will let you fetch real time data, and create/modify spreadsheets via Google sheets.\n\nThis is a great project for any Python developers that want to get started with MCP server development, and automation with AI agents!\n\n\ud83d\udc49 Links\n\ud83d\udd17 Code: https://github.com/pixegami/mcp-python-weather\n\ud83d\udd17 MCP Servers: https://github.com/modelcontextprotocol/servers\n\ud83c\udfa5 What is MCP? https://youtu.be/AdODsQdGHz0\n\n\ud83d\udcda Chapters\n00:00 Introduction\n02:33 MCP Server Overview\n04:31 Create an MCP Server\n08:58 Google Sheets MCP\n13:29 Using MCP tools in Claude Desktop\n\n#pixegami #ai",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/vzGkSn59rDU/default.jpg",
                        "width": 120,
                        "height": 90
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/vzGkSn59rDU/mqdefault.jpg",
                        "width": 320,
                        "height": 180
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/vzGkSn59rDU/hqdefault.jpg",
                        "width": 480,
                        "height": 360
                    },
                    "standard": {
                        "url": "https://i.ytimg.com/vi/vzGkSn59rDU/sddefault.jpg",
                        "width": 640,
                        "height": 480
                    },
                    "maxres": {
                        "url": "https://i.ytimg.com/vi/vzGkSn59rDU/maxresdefault.jpg",
                        "width": 1280,
                        "height": 720
                    }
                },
                "channelTitle": "pixegami",
                "tags": [
                    "mcp python",
                    "claude mcp",
                    "mcp ai",
                    "ai agent tutorial",
                    "python ai agent",
                    "python mcp",
                    "what is mcp",
                    "simple mcp",
                    "model context protocol",
                    "mcp server",
                    "mcp",
                    "mcp server python",
                    "mcp server tutorial",
                    "mcp server 101",
                    "how to build mcp server",
                    "python mcp server example",
                    "build an mcp server",
                    "mcp server project",
                    "getting started with mcp",
                    "mcp explained",
                    "mcp anthropic",
                    "github mcp server"
                ],
                "categoryId": "27",
                "liveBroadcastContent": "none",
                "localized": {
                    "title": "Build an MCP Server in 20 Minutes (with Python)",
                    "description": "Learn how to build an MCP server in Python and connect it to Claude Desktop and use it as an AI agent. This MCP server will let you fetch real time data, and create/modify spreadsheets via Google sheets.\n\nThis is a great project for any Python developers that want to get started with MCP server development, and automation with AI agents!\n\n\ud83d\udc49 Links\n\ud83d\udd17 Code: https://github.com/pixegami/mcp-python-weather\n\ud83d\udd17 MCP Servers: https://github.com/modelcontextprotocol/servers\n\ud83c\udfa5 What is MCP? https://youtu.be/AdODsQdGHz0\n\n\ud83d\udcda Chapters\n00:00 Introduction\n02:33 MCP Server Overview\n04:31 Create an MCP Server\n08:58 Google Sheets MCP\n13:29 Using MCP tools in Claude Desktop\n\n#pixegami #ai"
                },
                "defaultAudioLanguage": "en"
            },
            "contentDetails": {
                "duration": "PT19M21S",
                "dimension": "2d",
                "definition": "hd",
                "caption": "true",
                "licensedContent": true,
                "contentRating": {},
                "projection": "rectangular"
            },
            "statistics": {
                "viewCount": "2833",
                "likeCount": "111",
                "favoriteCount": "0",
                "commentCount": "8"
            }
        },
        {
            "kind": "youtube#video",
            "etag": "XJ11SOtmJYzbpG0QxBgo6Nj5stk",
            "id": "AdODsQdGHz0",
            "snippet": {
                "publishedAt": "2025-06-17T14:00:30Z",
                "channelId": "UCuxhTSKtnMJizinblLs9xOA",
                "title": "What is an MCP Server? Simply Explained in 15 Minutes",
                "description": "MCP (Model Context Protocol) gives AI agents superpowers.\n\nIt is an open standard that lets AI agents (LLMs) interact with the outside world \u2014 sort of a universal API (or a USB-C) for LLMs. Let's take a look at the problem it solves, how it works, and some examples.\n\nWith MCP servers, you will be able to enable AI agents to do anything that you could do with an external API: update spreadsheets, make a phone call, crawl the web, play a game (and probably thousands of other things).\n\n\ud83d\udc49 Links\n\ud83d\udd17 MCP Docs: https://modelcontextprotocol.io/introduction\n\ud83d\udd17 MCP Servers: https://github.com/modelcontextprotocol/servers\n\ud83d\udd17 Claude Desktop: https://claude.ai/download\n\n\ud83d\udcda Chapters\n00:00 What Is MCP?\n01:21 The Problem MCP Solves\n04:36 How MCP Works\n08:55 An Example Agent\n\n#pixegami #ai",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/AdODsQdGHz0/default.jpg",
                        "width": 120,
                        "height": 90
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/AdODsQdGHz0/mqdefault.jpg",
                        "width": 320,
                        "height": 180
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/AdODsQdGHz0/hqdefault.jpg",
                        "width": 480,
                        "height": 360
                    },
                    "standard": {
                        "url": "https://i.ytimg.com/vi/AdODsQdGHz0/sddefault.jpg",
                        "width": 640,
                        "height": 480
                    },
                    "maxres": {
                        "url": "https://i.ytimg.com/vi/AdODsQdGHz0/maxresdefault.jpg",
                        "width": 1280,
                        "height": 720
                    }
                },
                "channelTitle": "pixegami",
                "tags": [
                    "mcp tutorial",
                    "python mcp",
                    "ai mcp",
                    "mcp ai agents",
                    "what is mcp",
                    "mcp agents",
                    "autonomous agents",
                    "mcp servers",
                    "mcp ai",
                    "mcp claude",
                    "agent ai",
                    "ai agents",
                    "mcp service",
                    "mcp intro",
                    "mcp 101",
                    "how to use mcp",
                    "learn mcp",
                    "mcp explained",
                    "claude",
                    "ai",
                    "mcp agent",
                    "mcp for beginners",
                    "mcp explained simply",
                    "get started with mcp",
                    "mcp for python",
                    "how to write mcp",
                    "mcp vs rest api",
                    "mcp vs rest",
                    "why use mcp",
                    "mcp server",
                    "what is mcp server",
                    "mcp server tutorial"
                ],
                "categoryId": "27",
                "liveBroadcastContent": "none",
                "localized": {
                    "title": "What is an MCP Server? Simply Explained in 15 Minutes",
                    "description": "MCP (Model Context Protocol) gives AI agents superpowers.\n\nIt is an open standard that lets AI agents (LLMs) interact with the outside world \u2014 sort of a universal API (or a USB-C) for LLMs. Let's take a look at the problem it solves, how it works, and some examples.\n\nWith MCP servers, you will be able to enable AI agents to do anything that you could do with an external API: update spreadsheets, make a phone call, crawl the web, play a game (and probably thousands of other things).\n\n\ud83d\udc49 Links\n\ud83d\udd17 MCP Docs: https://modelcontextprotocol.io/introduction\n\ud83d\udd17 MCP Servers: https://github.com/modelcontextprotocol/servers\n\ud83d\udd17 Claude Desktop: https://claude.ai/download\n\n\ud83d\udcda Chapters\n00:00 What Is MCP?\n01:21 The Problem MCP Solves\n04:36 How MCP Works\n08:55 An Example Agent\n\n#pixegami #ai"
                },
                "defaultAudioLanguage": "en"
            },
            "contentDetails": {
                "duration": "PT14M17S",
                "dimension": "2d",
                "definition": "hd",
                "caption": "true",
                "licensedContent": true,
                "contentRating": {},
                "projection": "rectangular"
            },
            "statistics": {
                "viewCount": "2110",
                "likeCount": "112",
                "favoriteCount": "0",
                "commentCount": "7"
            }
        },
        {
            "kind": "youtube#video",
            "etag": "OIwNjKDGxRNaKGXepdQ-1pywgxM",
            "id": "uDUfZyNXFX0",
            "snippet": {
                "publishedAt": "2025-06-10T14:01:22Z",
                "channelId": "UCuxhTSKtnMJizinblLs9xOA",
                "title": "FastAPI for AI: Build an AI Endpoint in 30 Minutes",
                "description": "Learn how to build a FastAPI endpoint for your AI app in 30 mins.\n\nWe'll be using FastAPI (Python), and Gemini as our AI LLM model. Then we'll take a look at how to secure the endpoint with rate limiting, and with JWT tokens for authentication.\n\n\ud83d\udc49 Links\n\ud83d\udd17 Code: https://github.com/pixegami/fastapi-gemini-ai\n\ud83d\udd11 Get Your Gemini Key: https://aistudio.google.com/app/apikey\n\ud83c\udfa5 FastAPI on AWS Lambda: https://youtu.be/RGIM4JfsSk0\n\n\ud83d\udcda Chapters\n00:00 - Introduction\n01:29 - Project Overview\n02:34 - Setting Up\n04:13 - Create a FastAPI App\n06:46 - AI Integration (Gemini)\n08:11 - Custom System Prompt\n11:16 - Run the Server\n12:51 - Rate Limiting\n16:03 - Authentication with JWT\n22:38 - Finished Project\n\n#pixegami",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/uDUfZyNXFX0/default.jpg",
                        "width": 120,
                        "height": 90
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/uDUfZyNXFX0/mqdefault.jpg",
                        "width": 320,
                        "height": 180
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/uDUfZyNXFX0/hqdefault.jpg",
                        "width": 480,
                        "height": 360
                    },
                    "standard": {
                        "url": "https://i.ytimg.com/vi/uDUfZyNXFX0/sddefault.jpg",
                        "width": 640,
                        "height": 480
                    },
                    "maxres": {
                        "url": "https://i.ytimg.com/vi/uDUfZyNXFX0/maxresdefault.jpg",
                        "width": 1280,
                        "height": 720
                    }
                },
                "channelTitle": "pixegami",
                "tags": [
                    "fastapi tutorial",
                    "fastapi python",
                    "webdev",
                    "fastapi ai",
                    "fastapi for ai",
                    "build ai endpoint",
                    "gemini tutorial",
                    "python ai tutorial",
                    "ai fastapi",
                    "fastapi with ai",
                    "fastapi tutorial for ai",
                    "fastapi app",
                    "python fastapi",
                    "get started fastapi",
                    "how to use fastapi",
                    "rest api tutorial",
                    "api ai tutorial",
                    "gemini api",
                    "gemini python api",
                    "gemini python app",
                    "ai fastapi app",
                    "fastapi ai agent",
                    "fastapi ai project"
                ],
                "categoryId": "27",
                "liveBroadcastContent": "none",
                "localized": {
                    "title": "FastAPI for AI: Build an AI Endpoint in 30 Minutes",
                    "description": "Learn how to build a FastAPI endpoint for your AI app in 30 mins.\n\nWe'll be using FastAPI (Python), and Gemini as our AI LLM model. Then we'll take a look at how to secure the endpoint with rate limiting, and with JWT tokens for authentication.\n\n\ud83d\udc49 Links\n\ud83d\udd17 Code: https://github.com/pixegami/fastapi-gemini-ai\n\ud83d\udd11 Get Your Gemini Key: https://aistudio.google.com/app/apikey\n\ud83c\udfa5 FastAPI on AWS Lambda: https://youtu.be/RGIM4JfsSk0\n\n\ud83d\udcda Chapters\n00:00 - Introduction\n01:29 - Project Overview\n02:34 - Setting Up\n04:13 - Create a FastAPI App\n06:46 - AI Integration (Gemini)\n08:11 - Custom System Prompt\n11:16 - Run the Server\n12:51 - Rate Limiting\n16:03 - Authentication with JWT\n22:38 - Finished Project\n\n#pixegami"
                },
                "defaultAudioLanguage": "en"
            },
            "contentDetails": {
                "duration": "PT25M21S",
                "dimension": "2d",
                "definition": "hd",
                "caption": "true",
                "licensedContent": true,
                "contentRating": {},
                "projection": "rectangular"
            },
            "statistics": {
                "viewCount": "9060",
                "likeCount": "388",
                "favoriteCount": "0",
                "commentCount": "19"
            }
        },
        {
            "kind": "youtube#video",
            "etag": "wvk6BDo-qMXNkxBR0Flkxfyu0fU",
            "id": "gcqp3Fbv4_o",
            "snippet": {
                "publishedAt": "2025-06-03T14:01:08Z",
                "channelId": "UCuxhTSKtnMJizinblLs9xOA",
                "title": "Build a Simple RAG Pipeline in 30 Minutes!",
                "description": "Learn how to a simple, modular RAG pipeline in Python. This will let you add documents, generate embeddings, and evaluate (test) the pipeline quality, end-to-end with a single CLI command.\n\n\ud83d\udd17 Code: https://github.com/pixegami/simple-rag-pipeline\n\n\ud83d\udcda Chapters\n00:00 - Introduction\n02:01 - Pipeline Architecture\n04:43 - Set Up the Database\n09:05 - Set Up Core Components\n13:14 - Evaluation\n18:04 - Connect the Pipeline\n20:35 - Run the Pipeline\n23:39 - Upgrade and Run Again!\n\n#pixegami",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/gcqp3Fbv4_o/default.jpg",
                        "width": 120,
                        "height": 90
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/gcqp3Fbv4_o/mqdefault.jpg",
                        "width": 320,
                        "height": 180
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/gcqp3Fbv4_o/hqdefault.jpg",
                        "width": 480,
                        "height": 360
                    },
                    "standard": {
                        "url": "https://i.ytimg.com/vi/gcqp3Fbv4_o/sddefault.jpg",
                        "width": 640,
                        "height": 480
                    },
                    "maxres": {
                        "url": "https://i.ytimg.com/vi/gcqp3Fbv4_o/maxresdefault.jpg",
                        "width": 1280,
                        "height": 720
                    }
                },
                "channelTitle": "pixegami",
                "tags": [
                    "python rag pipeline",
                    "openai",
                    "lancedb",
                    "pdf documents",
                    "ai pdf query",
                    "rag tutorial",
                    "python ai",
                    "document ai",
                    "conversational ai",
                    "information retrieval",
                    "llm",
                    "vector database",
                    "embeddings",
                    "text extraction",
                    "pdf processing",
                    "ai chatbot",
                    "semantic search",
                    "ai development",
                    "machine learning",
                    "data science",
                    "coding tutorial",
                    "ai project",
                    "python programming",
                    "openai api",
                    "lancedb integration",
                    "ai testing",
                    "rag evaluation",
                    "retrieval augmented generation"
                ],
                "categoryId": "27",
                "liveBroadcastContent": "none",
                "localized": {
                    "title": "Build a Simple RAG Pipeline in 30 Minutes!",
                    "description": "Learn how to a simple, modular RAG pipeline in Python. This will let you add documents, generate embeddings, and evaluate (test) the pipeline quality, end-to-end with a single CLI command.\n\n\ud83d\udd17 Code: https://github.com/pixegami/simple-rag-pipeline\n\n\ud83d\udcda Chapters\n00:00 - Introduction\n02:01 - Pipeline Architecture\n04:43 - Set Up the Database\n09:05 - Set Up Core Components\n13:14 - Evaluation\n18:04 - Connect the Pipeline\n20:35 - Run the Pipeline\n23:39 - Upgrade and Run Again!\n\n#pixegami"
                },
                "defaultAudioLanguage": "en"
            },
            "contentDetails": {
                "duration": "PT27M59S",
                "dimension": "2d",
                "definition": "hd",
                "caption": "true",
                "licensedContent": true,
                "contentRating": {},
                "projection": "rectangular"
            },
            "statistics": {
                "viewCount": "2923",
                "likeCount": "128",
                "favoriteCount": "0",
                "commentCount": "10"
            }
        },
        {
            "kind": "youtube#video",
            "etag": "-GH9K_okF7dKHZglOrnWPF3ZyYw",
            "id": "LUJw9eTUTYQ",
            "snippet": {
                "publishedAt": "2025-02-01T14:00:19Z",
                "channelId": "UCuxhTSKtnMJizinblLs9xOA",
                "title": "Run DeepSeek R1 Locally \u2014 Free AI That Actually Works!",

# Video Data Extraction

In [39]:
title=[]
desc=[]
thumbnails=[]
tags=[]
duration=[]
views=[]
likes=[]
comments=[]
vid=[]
for item in response['items']:
    vid.append(item['id'])
    try:title.append(item['snippet']['title'])
    except:title.append(None)
    try:desc.append(item['snippet']['description'])
    except:desc.append(None)
    try:thumbnails.append(item['snippet']['thumbnails']['medium']['url'])
    except:thumbnails.append(None)
    try:tags.append(item['snippet']['tags'])
    except:tags.append(None)

    time=item['contentDetails']['duration']
    try:time=f"{time[time.index('T')+1:time.index('H')]}:{time[time.index('H')+1:time.index('M')]}:{time[time.index('M')+1:time.index('S')]}"
    except:
        try:time=f"{time[time.index('T')+1:time.index('M')]}:{time[time.index('M')+1:time.index('S')]}"
        except:
            try:time=f"00:{time[time.index('T')+1:time.index('S')]}"
            except:time='00:00:00'
        
    duration.append(time)
    #duration.append(item['contentDetails']['duration'])
    views.append(item['statistics']['viewCount'])
    likes.append(item['statistics']["likeCount"])
    comments.append(item['statistics']['commentCount'])

In [40]:
len(title)

50

In [41]:
tags

[None,
 None,
 ['Keywords live session',
  'career advice',
  'programming',
  'database design',
  'project ideas',
  'job market',
  'education',
  'machine learning',
  'software development',
  'networking'],
 None,
 ['coding',
  'hindi',
  'javascript',
  'web developer',
  'react',
  'quality',
  'reactjs',
  'tech interviews',
  'coding interviews',
  'python',
  'django',
  'machine learning',
  'python for beginners',
  'AI',
  'Data Science'],
 None,
 None,
 ['coding',
  'hindi',
  'javascript',
  'web developer',
  'react',
  'quality',
  'reactjs',
  'tech interviews',
  'coding interviews',
  'python',
  'django',
  'machine learning',
  'python for beginners',
  'AI',
  'Data Science'],
 None,
 None,
 None,
 None,
 ['coding',
  'hindi',
  'javascript',
  'web developer',
  'react',
  'quality',
  'reactjs',
  'tech interviews',
  'coding interviews',
  'python',
  'django',
  'machine learning',
  'python for beginners',
  'AI',
  'Data Science'],
 ['coding',
  'hindi',
  'javascript',
  'web developer',
  'react',
  'quality',
  'reactjs',
  'tech interviews',
  'coding interviews',
  'python',
  'django',
  'machine learning',
  'python for beginners',
  'AI',
  'Data Science'],
 ['coding',
  'hindi',
  'javascript',
  'web developer',
  'react',
  'quality',
  'reactjs',
  'tech interviews',
  'coding interviews',
  'python',
  'django',
  'machine learning',
  'python for beginners',
  'AI',
  'Data Science'],
 ['coding',
  'hindi',
  'javascript',
  'web developer',
  'react',
  'quality',
  'reactjs',
  'tech interviews',
  'coding interviews',
  'python',
  'django',
  'machine learning',
  'python for beginners',
  'AI',
  'Data Science'],
 ['coding',
  'hindi',
  'javascript',
  'web developer',
  'react',
  'quality',
  'reactjs',
  'tech interviews',
  'coding interviews',
  'python',
  'django',
  'machine learning',
  'python for beginners',
  'AI',
  'Data Science',
  'artificial intelligence'],
 ['coding',
  'hindi',
  'javascript',
  'web developer',
  'react',
  'quality',
  'reactjs',
  'tech interviews',
  'coding interviews',
  'python',
  'django',
  'machine learning',
  'python for beginners',
  'AI',
  'Data Science'],
 ['coding',
  'hindi',
  'javascript',
  'web developer',
  'react',
  'quality',
  'reactjs',
  'tech interviews',
  'coding interviews',
  'python',
  'django',
  'machine learning',
  'python for beginners',
  'AI',
  'Data Science'],
 ['coding',
  'hindi',
  'javascript',
  'web developer',
  'react',
  'quality',
  'reactjs',
  'tech interviews',
  'coding interviews',
  'python',
  'django',
  'machine learning',
  'python for beginners',
  'AI',
  'Data Science'],
 ['coding',
  'hindi',
  'javascript',
  'web developer',
  'react',
  'quality',
  'reactjs',
  'tech interviews',
  'coding interviews',
  'python',
  'django',
  'machine learning',
  'python for beginners',
  'AI',
  'Data Science'],
 ['coding',
  'hindi',
  'javascript',
  'web developer',
  'react',
  'quality',
  'reactjs',
  'tech interviews',
  'coding interviews',
  'python',
  'django',
  'machine learning',
  'python for beginners',
  'AI',
  'Data Science'],
 ['coding',
  'hindi',
  'javascript',
  'web developer',
  'react',
  'quality',
  'reactjs',
  'tech interviews',
  'coding interviews',
  'python',
  'django',
  'machine learning',
  'python for beginners',
  'AI',
  'Data Science',
  'dependency Injection',
  'fastapi'],
 ['coding',
  'hindi',
  'javascript',
  'web developer',
  'react',
  'quality',
  'reactjs',
  'tech interviews',
  'coding interviews',
  'python',
  'django',
  'machine learning',
  'python for beginners',
  'AI',
  'Data Science',
  'long polling',
  'server sent events',
  'Web sockets',
  'LLM Chat app'],
 None,
 ['coding',
  'hindi',
  'javascript',
  'web developer',
  'react',
  'quality',
  'reactjs',
  'tech interviews',
  'coding interviews',
  'python',
  'django',
  'machine learning',
  'python for beginners',
  'AI',
  'Data Science'],
 ['coding',
  'hindi',
  'javascript',
  'web developer',
  'react',
  'quality',
  'reactjs',
  'tech interviews',
  'coding interviews',
  'python',
  'django',
  'machine learning',
  'python for beginners',
  'AI',
  'Data Science'],
 None,
 None,
 None,
 None,
 None,
 None,
 ['coding',
  'hindi',
  'javascript',
  'web developer',
  'react',
  'quality',
  'reactjs',
  'tech interviews',
  'coding interviews',
  'python',
  'django',
  'machine learning',
  'python for beginners',
  'AI',
  'Data Science',
  'FastAPI',
  'pydantic',
  'api with python'],
 ['coding',
  'hindi',
  'javascript',
  'web developer',
  'react',
  'quality',
  'reactjs',
  'tech interviews',
  'coding interviews',
  'python',
  'django',
  'machine learning',
  'python for beginners',
  'AI',
  'Data Science'],
 None,
 None,
 ['coding',
  'hindi',
  'javascript',
  'web developer',
  'react',
  'quality',
  'reactjs',
  'tech interviews',
  'coding interviews',
  'python',
  'django',
  'machine learning',
  'python for beginners',
  'AI',
  'Data Science'],
 ['coding',
  'hindi',
  'javascript',
  'web developer',
  'react',
  'quality',
  'reactjs',
  'tech interviews',
  'coding interviews',
  'python',
  'django',
  'machine learning',
  'python for beginners',
  'AI',
  'Data Science',
  'data science cohort',
  'machine learning live class'],
 ['coding',
  'hindi',
  'javascript',
  'web developer',
  'react',
  'quality',
  'reactjs',
  'tech interviews',
  'coding interviews',
  'python',
  'django',
  'machine learning',
  'python for beginners',
  'AI',
  'Data Science',
  'Docker',
  'Linux',
  'Containers'],
 None,
 None,
 ['coding',
  'hindi',
  'javascript',
  'web developer',
  'react',
  'quality',
  'reactjs',
  'tech interviews',
  'coding interviews',
  'python',
  'django',
  'machine learning',
  'python for beginners',
  'AI',
  'Data Science',
  'GenAI',
  'langchain'],
 ['coding',
  'hindi',
  'javascript',
  'web developer',
  'react',
  'quality',
  'reactjs',
  'tech interviews',
  'coding interviews',
  'python',
  'django',
  'machine learning',
  'python for beginners',
  'AI',
  'Data Science'],
 ['coding',
  'hindi',
  'javascript',
  'web developer',
  'react',
  'quality',
  'reactjs',
  'tech interviews',
  'coding interviews',
  'python',
  'django',
  'machine learning',
  'python for beginners',
  'AI',
  'Data Science'],
 ['coding',
  'hindi',
  'javascript',
  'web developer',
  'react',
  'quality',
  'reactjs',
  'tech interviews',
  'coding interviews',
  'python',
  'django',
  'machine learning',
  'python for beginners',
  'AI',
  'Data Science'],
 ['coding',
  'hindi',
  'javascript',
  'web developer',
  'react',
  'quality',
  'reactjs',
  'tech interviews',
  'coding interviews',
  'python',
  'django',
  'machine learning',
  'python for beginners',
  'AI',
  'Data Science'],
 None,
 None,
 None]

In [42]:
a='PT24M41S'
#a.index('M')
a[a.index('M')+1:a.index('S')]

'41'

In [43]:
duration

['1:26:33',
 '1:18',
 '1:10:59',
 '2:9',
 '19:25',
 '2:10',
 '1:37',
 '3:36:58',
 '3:6:50',
 '1:48',
 '1:29',
 '2:18:45',
 '16:30',
 '15:57',
 '17:23',
 '10:32',
 '16:20',
 '19:25',
 '1:23:25',
 '12:49',
 '8:38',
 '7:54',
 '18:24',
 '00:00:00',
 '2:6:17',
 '1:5:10',
 '22:47',
 '1:24',
 '1:52:17',
 '1:22',
 '1:45',
 '00:56',
 '1:30',
 '24:12',
 '16:47',
 '1:10:20',
 '1:31:3',
 '00:00:00',
 '26:29',
 '19:2',
 '1:27',
 '37:32',
 '13:19',
 '26:58',
 '11:5',
 '9:31',
 '13:25',
 '00:46',
 '00:46',
 '41:19']

In [44]:
views

['22681',
 '38765',
 '24022',
 '54906',
 '114485',
 '92513',
 '70619',
 '88849',
 '43178',
 '52456',
 '62874',
 '61353',
 '33953',
 '67636',
 '45670',
 '22981',
 '104215',
 '129899',
 '35771',
 '35163',
 '14032',
 '73563',
 '13755',
 '28508',
 '38052',
 '36558',
 '47787',
 '20941',
 '20312',
 '19595',
 '30911',
 '52380',
 '40462',
 '84162',
 '116822',
 '16509',
 '19731',
 '29273',
 '95767',
 '112559',
 '16328',
 '15297',
 '146761',
 '204760',
 '97371',
 '36542',
 '119075',
 '9748',
 '16105',
 '21845']

# Making the Video DataFrame

In [45]:
vdf=pd.DataFrame(
    {
        'VID':vid,
        'Title':title,
        'Duration':duration,
        'Views':views,
        'Likes':likes,
        'Comments':comments,
        'Thumbnail':thumbnails,
        'Tags':tags,
        'Description':desc
    }
)

In [46]:
vdf

,VID,Title,Duration,Views,Likes,Comments,Thumbnail,Tags,Description
0,wS1i9WmLKY0,Chai aur python pe charcha,1:26:33,22681,1228,78,https://i.ytimg.com/vi/wS1i9WmLKY0/mqdefault.jpg,None,https://hitesh.ai/udemy-py
1,OFc067iLnos,Demo to sabhi AI product ka achha hi hota h,1:18,38765,2791,37,https://i.ytimg.com/vi/OFc067iLnos/mqdefault.jpg,None,Demo to sabhi AI product ka achha hi hota h
2,vtlYTK_0Zb0,Late night chai pe charcha,1:10:59,24022,1553,52,https://i.ytimg.com/vi/vtlYTK_0Zb0/mqdefault.jpg,"[Keywords live session, career advice, program...",https://courses.chaicode.com/learn\n\nAll coho...
3,MtoZo8XQLpA,"You cannot learn anything at ay time, subject ...",2:9,54906,5248,102,https://i.ytimg.com/vi/MtoZo8XQLpA/mqdefault.jpg,None,"You cannot learn anything at ay time, subject ..."
4,tysDxjfgLMg,What is n8n in Hindi. Fastest and easiest self...,19:25,114485,2364,193,https://i.ytimg.com/vi/tysDxjfgLMg/mqdefault.jpg,"[coding, hindi, javascript, web developer, rea...","Is video me hum baat krenge, Langgraph, n8n an..."
5,1yixo_zg-JY,"Life me ye phase to zrur aata h sabke, bs baat...",2:10,92513,8992,227,https://i.ytimg.com/vi/1yixo_zg-JY/mqdefault.jpg,None,"Life me ye phase to zrur aata h sabke, bs baat..."
6,Re9OTYhegB0,Different path,1:37,70619,4501,111,https://i.ytimg.com/vi/Re9OTYhegB0/mqdefault.jpg,None,Different path
7,c8Z73cVl6x4,"Build a full stack project with NextJS, NextAu...",3:36:58,88849,2861,359,https://i.ytimg.com/vi/c8Z73cVl6x4/mqdefault.jpg,"[coding, hindi, javascript, web developer, rea...",Check out Imagekit here: https://hitesh.ai/ima...
8,5t5-R55wA5g,Demo Day - Building Leetlab for iPhone prize,3:6:50,43178,1430,63,https://i.ytimg.com/vi/5t5-R55wA5g/mqdefault.jpg,None,https://hitesh.ai/cohort\nye live stream hamar...
9,bRP_pmDAIcI,Singular focus and self trust,1:48,52456,5245,103,https://i.ytimg.com/vi/bRP_pmDAIcI/mqdefault.jpg,None,Singular focus and self trust
10,rMAn6ikCf84,Luck is a magical button in life.,1:29,62874,4658,132,https://i.ytimg.com/vi/rMAn6ikCf84/mqdefault.jpg,None,Luck is a magical button in life. \nit surely ...
11,3M9Lmlh3ek4,Chai pe charcha | Demo day,2:18:45,61353,2061,89,https://i.ytimg.com/vi/3M9Lmlh3ek4/mqdefault.jpg,None,https://hitesh.ai/genai-cohort\nThe new GenAI ...
12,UsNdgJY6tCY,A common Production mistake in react,16:30,33953,2194,396,https://i.ytimg.com/vi/UsNdgJY6tCY/mqdefault.jpg,"[coding, hindi, javascript, web developer, rea...","Welcome to chai aur code, a coding/programming..."
13,7W1me-WoWXo,Project vs Product Mindset for new software en...,15:57,67636,4296,217,https://i.ytimg.com/vi/7W1me-WoWXo/mqdefault.jpg,"[coding, hindi, javascript, web developer, rea...",Check out more at https://chaicode.com \n\nWel...
14,GWvW96WNB6Q,Engineering College is just to mentally break ...,17:23,45670,3823,519,https://i.ytimg.com/vi/GWvW96WNB6Q/mqdefault.jpg,"[coding, hindi, javascript, web developer, rea...","Welcome to chai aur code, a coding/programming..."
15,kDLrIV59PdU,What are reactive databases,10:32,22981,1522,228,https://i.ytimg.com/vi/kDLrIV59PdU/mqdefault.jpg,"[coding, hindi, javascript, web developer, rea...","Welcome to chai aur code, a coding/programming..."
16,6cELK1YG4iM,Indian AI is on 23 downloads after 2 days,16:20,104215,4840,594,https://i.ytimg.com/vi/6cELK1YG4iM/mqdefault.jpg,"[coding, hindi, javascript, web developer, rea...","Welcome to chai aur code, a coding/programming..."
17,6RHYkwJPJlM,GenAI with python cohort 2 is here,19:25,129899,683,229,https://i.ytimg.com/vi/6RHYkwJPJlM/mqdefault.jpg,"[coding, hindi, javascript, web developer, rea...",https://hitesh.ai/genai-cohort\nuseCode HITESH...
18,rE-y-yMIeok,Complete Pydantic course in Hindi,1:23:25,35771,1843,803,https://i.ytimg.com/vi/rE-y-yMIeok/mqdefault.jpg,"[coding, hindi, javascript, web developer, rea...",For courses and cohort: https://www.chaicode.c...
19,VJVfWWdtJ4c,Lets talk about system design course,12:49,35163,1763,155,https://i.ytimg.com/vi/VJVfWWdtJ4c/mqdefault.jpg,"[coding, hindi, javascript, web developer, rea...",Check https://www.chaicode.com for more info\n...
20,dz5C-r0Z9AA,DSA with C++ cohort Launch,8:38,14032,604,201,https://i.ytimg.com/vi/dz5C-r0Z9AA/mqdefault.jpg,"[coding, hindi, javascript, web developer, rea...",DSA cohort link: https://hitesh.ai/dsa-cpp\nCl...
21,M9BoBI5kQxI,Superior Stack Syndrome,7:54,73563,4253,535,https://i.ytimg.com/vi/M9BoBI5kQxI/mqdefault.jpg,"[coding, hindi, javascript, web developer, rea...",Check out https://www.chaicode.com for more co...
22,8QZK0xMrsII,Dependency Injection in Python,18:24,13755,766,182,https://i.ytimg.com/vi/8QZK0xMrsII/mqdefault.jpg,"[coding, hindi, javascript, web developer, rea...","https://www.chaicode.com\nfor more cohorts, li..."
23,_CCyMWSZNU4,"Long polling, server sent Events and Web Socke...",00:00:00,28508,1655,729,https://i.ytimg.com/vi/_CCyMWSZNU4/mqdefault.jpg,"[coding, hindi, javascript, web developer, rea...",https://www.chaicode.com\nFor more content and...
24,ZoAtc-EqeUQ,Cohort Demo Day | Project reviews,2:6:17,38052,1226,83,https://i.ytimg.com/vi/ZoAtc-EqeUQ/mqdefault.jpg,None,Thanks for joining our exclusive live broadcas...
25,yKTEC1Y5bEQ,Complete Streamlit course for python developers,1:5:10,36558,1827,503,https://i.ytimg.com/vi/yKTEC1Y5bEQ/mqdefault.jpg,"[coding, hindi, javascript, web developer, rea...","Welcome to chai aur code, a coding/programming..."
26,8mk85fyzevc,Don't create virtual environment in python in ...,22:47,47787,2335,514,https://i.ytimg.com/vi/8mk85fyzevc/mqdefault.jpg,"[coding, hindi, javascript, web developer, rea...","To learn web development, GenAI, DevOps or Dat..."
27,N47ERzX3odo,Project: Cohort Team Management,1:24,20941,933,14,https://i.ytimg.com/vi/N47ERzX3odo/mqdefault.jpg,None,Project: Cohort Team Management
28,Rwm2IQa0Lvs,Chai pe charcha ☕️,1:52:17,20312,1064,22,https://i.ytimg.com/vi/Rwm2IQa0Lvs/mqdefault.jpg,None,For DevOps: https://hitesh.ai/devops-cohort\nF...
29,04P-UpcByYs,Project : Squad Up 😎,1:22,19595,885,12,https://i.ytimg.com/vi/04P-UpcByYs/mqdefault.jpg,None,Project : Squad Up 😎
30,7_hXtlT7GtM,"The Chai theme has reached a milestone of 100,...",1:45,30911,2710,58,https://i.ytimg.com/vi/7_hXtlT7GtM/mqdefault.jpg,None,"The Chai theme has reached a milestone of 100,..."
31,hcBWSqytPeY,Prioritize Health First,00:56,52380,2958,28,https://i.ytimg.com/vi/hcBWSqytPeY/mqdefault.jpg,None,Prioritize Health First 😃
32,ueP2PHK3w2s,Full stack data science cohort | Live classes ...,1:30,40462,1811,30,https://i.ytimg.com/vi/ueP2PHK3w2s/mqdefault.jpg,None,
33,foGklduxhM0,FastAPI crash course in Hindi,24:12,84162,4047,1345,https://i.ytimg.com/vi/foGklduxhM0/mqdefault.jpg,"[coding, hindi, javascript, web developer, rea...",Our new Live cohorts\nhttps://hitesh.ai/data-s...
34,iSNvKaVtwTU,Talking to a course pirate on call,16:47,116822,6420,962,https://i.ytimg.com/vi/iSNvKaVtwTU/mqdefault.jpg,"[coding, hindi, javascript, web developer, rea...",This video should not exists.\nFOCUS on learni...
35,4BQMKkq1T5E,600K special Live ☕️,1:10:20,16509,1145,42,https://i.ytimg.com/vi/4BQMKkq1T5E/mqdefault.jpg,None,https://hitesh.ai/data-science\nhttps://hitesh...
36,tuXgFeRBvVs,Chai pe charcha GenAI ki,1:31:3,19731,908,32,https://i.ytimg.com/vi/tuXgFeRBvVs/mqdefault.jpg,None,https://hitesh.ai/genai-cohort \nhttps://hites...
37,Fw3FezexzV0,"100 free seats every month, DSA sheet, Live cl...",00:00:00,29273,1438,129,https://i.ytimg.com/vi/Fw3FezexzV0/mqdefault.jpg,"[coding, hindi, javascript, web developer, rea...",Ye ha hamara CodingHero V2.\nHappy to announce...
38,Kjd-SWpe1do,Full Stack data science cohort | Live batch,26:29,95767,1112,234,https://i.ytimg.com/vi/Kjd-SWpe1do/mqdefault.jpg,"[coding, hindi, javascript, web developer, rea...",https://hitesh.ai/data-science\nUse DISCORD25 ...
39,oBLpqSHc3lA,DevOps for Developers cohort | Live classes la...,19:2,112559,1073,194,https://i.ytimg.com/vi/oBLpqSHc3lA/mqdefault.jpg,"[coding, hindi, javascript, web developer, rea...",https://hitesh.ai/devops-cohort\nfor 1st 100 u...
40,05WtC2Czc5c,GenAI for developers,1:27,16328,1064,19,https://i.ytimg.com/vi/05WtC2Czc5c/mqdefault.jpg,None,
41,9vqlZneYq7w,Late night stream | just tech talks,37:32,15297,1135,38,https://i.ytimg.com/vi/9vqlZneYq7w/mqdefault.jpg,None,https://hitesh.ai/genai-cohort - GenAI for dev...
42,VNb_LawBBWU,GenAI for developers cohort launch,13:19,146761,1996,356,https://i.ytimg.com/vi/VNb_LawBBWU/mqdefault.jpg,"[coding, hindi, javascript, web developer, rea...",https://hitesh.ai/genai-cohort\nuse code HITES...
43,dZyQNy3-HjU,What are MCP servers | Explained in Hindi,26:58,204760,6960,295,https://i.ytimg.com/vi/dZyQNy3-HjU/mqdefault.jpg,"[coding, hindi, javascript, web developer, rea...",https://hitesh.ai/cohort\n\nWelcome to chai au...
44,KnIye1fJF80,AI is 90% marketing and 10% reality,11:5,97371,4290,320,https://i.ytimg.com/vi/KnIye1fJF80/mqdefault.jpg,"[coding, hindi, javascript, web developer, rea...","Welcome to chai aur code, a coding/programming..."
45,1i8R-iJiEi8,Behind the scene of I build a SAAS with AI,9:31,36542,1900,225,https://i.ytimg.com/vi/1i8R-iJiEi8/mqdefault.jpg,"[coding, hindi, javascript, web developer, rea...",https://hitesh.ai/cohort\n\nWelcome to chai au...
46,af62B4lWuLo,Getting attacked from all side,13:25,119075,8291,1048,https://i.ytimg.com/vi/af62B4lWuLo/mqdefault.jpg,"[coding, hindi, javascript, web developer, rea...","Welcome to chai aur code, a coding/programming..."
47,RHng5svxT58,AI reviews AI,00:46,9748,372,8,https://i.ytimg.com/vi/RHng5svxT58/mqdefault.jpg,None,
48,07vViFYgysM,AI reviews AI,00:46,16105,866,8,https://i.ytimg.com/vi/07vViFYgysM/mqdefault.jpg,None,
49,bbn6feSeUjI,Chai pe charcha,41:19,21845,1554,61,https://i.ytimg.com/vi/bbn6feSeUjI/mqdefault.jpg,None,https://hitesh.ai/cohort

In [47]:
str(vdf['Tags'].iloc[0])

'None'

In [48]:
vdf['Tags'].astype(str).iloc[0]

'None'

In [49]:
vdf['Tags']=vdf['Tags'].astype(str).str.translate(str.maketrans('','',"[]'"))

In [50]:
vdf['Tags']

0                                                  None
1                                                  None
2     Keywords live session, career advice, programm...
3                                                  None
4     coding, hindi, javascript, web developer, reac...
5                                                  None
6                                                  None
7     coding, hindi, javascript, web developer, reac...
8                                                  None
9                                                  None
10                                                 None
11                                                 None
12    coding, hindi, javascript, web developer, reac...
13    coding, hindi, javascript, web developer, reac...
14    coding, hindi, javascript, web developer, reac...
15    coding, hindi, javascript, web developer, reac...
16    coding, hindi, javascript, web developer, reac...
17    coding, hindi, javascript, web developer, reac...
18    coding, hindi, javascript, web developer, reac...
19    coding, hindi, javascript, web developer, reac...
20    coding, hindi, javascript, web developer, reac...
21    coding, hindi, javascript, web developer, reac...
22    coding, hindi, javascript, web developer, reac...
23    coding, hindi, javascript, web developer, reac...
24                                                 None
25    coding, hindi, javascript, web developer, reac...
26    coding, hindi, javascript, web developer, reac...
27                                                 None
28                                                 None
29                                                 None
30                                                 None
31                                                 None
32                                                 None
33    coding, hindi, javascript, web developer, reac...
34    coding, hindi, javascript, web developer, reac...
35                                                 None
36                                                 None
37    coding, hindi, javascript, web developer, reac...
38    coding, hindi, javascript, web developer, reac...
39    coding, hindi, javascript, web developer, reac...
40                                                 None
41                                                 None
42    coding, hindi, javascript, web developer, reac...
43    coding, hindi, javascript, web developer, reac...
44    coding, hindi, javascript, web developer, reac...
45    coding, hindi, javascript, web developer, reac...
46    coding, hindi, javascript, web developer, reac...
47                                                 None
48                                                 None
49                                                 None
Name: Tags, dtype: object

In [51]:
a=vdf['Title']+vdf['Description']+vdf['Tags']

In [52]:
a.iloc[0]

'Chai aur python pe charchahttps://hitesh.ai/udemy-pyNone'

In [61]:
j=vdf.to_json(orient='records')

In [62]:
text=json.dumps(j,indent=10)

In [64]:
vdf

,VID,Title,Duration,Views,Likes,Comments,Thumbnail,Tags,Description
0,wS1i9WmLKY0,Chai aur python pe charcha,1:26:33,22681,1228,78,https://i.ytimg.com/vi/wS1i9WmLKY0/mqdefault.jpg,None,https://hitesh.ai/udemy-py
1,OFc067iLnos,Demo to sabhi AI product ka achha hi hota h,1:18,38765,2791,37,https://i.ytimg.com/vi/OFc067iLnos/mqdefault.jpg,None,Demo to sabhi AI product ka achha hi hota h
2,vtlYTK_0Zb0,Late night chai pe charcha,1:10:59,24022,1553,52,https://i.ytimg.com/vi/vtlYTK_0Zb0/mqdefault.jpg,"Keywords live session, career advice, programm...",https://courses.chaicode.com/learn\n\nAll coho...
3,MtoZo8XQLpA,"You cannot learn anything at ay time, subject ...",2:9,54906,5248,102,https://i.ytimg.com/vi/MtoZo8XQLpA/mqdefault.jpg,None,"You cannot learn anything at ay time, subject ..."
4,tysDxjfgLMg,What is n8n in Hindi. Fastest and easiest self...,19:25,114485,2364,193,https://i.ytimg.com/vi/tysDxjfgLMg/mqdefault.jpg,"coding, hindi, javascript, web developer, reac...","Is video me hum baat krenge, Langgraph, n8n an..."
5,1yixo_zg-JY,"Life me ye phase to zrur aata h sabke, bs baat...",2:10,92513,8992,227,https://i.ytimg.com/vi/1yixo_zg-JY/mqdefault.jpg,None,"Life me ye phase to zrur aata h sabke, bs baat..."
6,Re9OTYhegB0,Different path,1:37,70619,4501,111,https://i.ytimg.com/vi/Re9OTYhegB0/mqdefault.jpg,None,Different path
7,c8Z73cVl6x4,"Build a full stack project with NextJS, NextAu...",3:36:58,88849,2861,359,https://i.ytimg.com/vi/c8Z73cVl6x4/mqdefault.jpg,"coding, hindi, javascript, web developer, reac...",Check out Imagekit here: https://hitesh.ai/ima...
8,5t5-R55wA5g,Demo Day - Building Leetlab for iPhone prize,3:6:50,43178,1430,63,https://i.ytimg.com/vi/5t5-R55wA5g/mqdefault.jpg,None,https://hitesh.ai/cohort\nye live stream hamar...
9,bRP_pmDAIcI,Singular focus and self trust,1:48,52456,5245,103,https://i.ytimg.com/vi/bRP_pmDAIcI/mqdefault.jpg,None,Singular focus and self trust
10,rMAn6ikCf84,Luck is a magical button in life.,1:29,62874,4658,132,https://i.ytimg.com/vi/rMAn6ikCf84/mqdefault.jpg,None,Luck is a magical button in life. \nit surely ...
11,3M9Lmlh3ek4,Chai pe charcha | Demo day,2:18:45,61353,2061,89,https://i.ytimg.com/vi/3M9Lmlh3ek4/mqdefault.jpg,None,https://hitesh.ai/genai-cohort\nThe new GenAI ...
12,UsNdgJY6tCY,A common Production mistake in react,16:30,33953,2194,396,https://i.ytimg.com/vi/UsNdgJY6tCY/mqdefault.jpg,"coding, hindi, javascript, web developer, reac...","Welcome to chai aur code, a coding/programming..."
13,7W1me-WoWXo,Project vs Product Mindset for new software en...,15:57,67636,4296,217,https://i.ytimg.com/vi/7W1me-WoWXo/mqdefault.jpg,"coding, hindi, javascript, web developer, reac...",Check out more at https://chaicode.com \n\nWel...
14,GWvW96WNB6Q,Engineering College is just to mentally break ...,17:23,45670,3823,519,https://i.ytimg.com/vi/GWvW96WNB6Q/mqdefault.jpg,"coding, hindi, javascript, web developer, reac...","Welcome to chai aur code, a coding/programming..."
15,kDLrIV59PdU,What are reactive databases,10:32,22981,1522,228,https://i.ytimg.com/vi/kDLrIV59PdU/mqdefault.jpg,"coding, hindi, javascript, web developer, reac...","Welcome to chai aur code, a coding/programming..."
16,6cELK1YG4iM,Indian AI is on 23 downloads after 2 days,16:20,104215,4840,594,https://i.ytimg.com/vi/6cELK1YG4iM/mqdefault.jpg,"coding, hindi, javascript, web developer, reac...","Welcome to chai aur code, a coding/programming..."
17,6RHYkwJPJlM,GenAI with python cohort 2 is here,19:25,129899,683,229,https://i.ytimg.com/vi/6RHYkwJPJlM/mqdefault.jpg,"coding, hindi, javascript, web developer, reac...",https://hitesh.ai/genai-cohort\nuseCode HITESH...
18,rE-y-yMIeok,Complete Pydantic course in Hindi,1:23:25,35771,1843,803,https://i.ytimg.com/vi/rE-y-yMIeok/mqdefault.jpg,"coding, hindi, javascript, web developer, reac...",For courses and cohort: https://www.chaicode.c...
19,VJVfWWdtJ4c,Lets talk about system design course,12:49,35163,1763,155,https://i.ytimg.com/vi/VJVfWWdtJ4c/mqdefault.jpg,"coding, hindi, javascript, web developer, reac...",Check https://www.chaicode.com for more info\n...
20,dz5C-r0Z9AA,DSA with C++ cohort Launch,8:38,14032,604,201,https://i.ytimg.com/vi/dz5C-r0Z9AA/mqdefault.jpg,"coding, hindi, javascript, web developer, reac...",DSA cohort link: https://hitesh.ai/dsa-cpp\nCl...
21,M9BoBI5kQxI,Superior Stack Syndrome,7:54,73563,4253,535,https://i.ytimg.com/vi/M9BoBI5kQxI/mqdefault.jpg,"coding, hindi, javascript, web developer, reac...",Check out https://www.chaicode.com for more co...
22,8QZK0xMrsII,Dependency Injection in Python,18:24,13755,766,182,https://i.ytimg.com/vi/8QZK0xMrsII/mqdefault.jpg,"coding, hindi, javascript, web developer, reac...","https://www.chaicode.com\nfor more cohorts, li..."
23,_CCyMWSZNU4,"Long polling, server sent Events and Web Socke...",00:00:00,28508,1655,729,https://i.ytimg.com/vi/_CCyMWSZNU4/mqdefault.jpg,"coding, hindi, javascript, web developer, reac...",https://www.chaicode.com\nFor more content and...
24,ZoAtc-EqeUQ,Cohort Demo Day | Project reviews,2:6:17,38052,1226,83,https://i.ytimg.com/vi/ZoAtc-EqeUQ/mqdefault.jpg,None,Thanks for joining our exclusive live broadcas...
25,yKTEC1Y5bEQ,Complete Streamlit course for python developers,1:5:10,36558,1827,503,https://i.ytimg.com/vi/yKTEC1Y5bEQ/mqdefault.jpg,"coding, hindi, javascript, web developer, reac...","Welcome to chai aur code, a coding/programming..."
26,8mk85fyzevc,Don't create virtual environment in python in ...,22:47,47787,2335,514,https://i.ytimg.com/vi/8mk85fyzevc/mqdefault.jpg,"coding, hindi, javascript, web developer, reac...","To learn web development, GenAI, DevOps or Dat..."
27,N47ERzX3odo,Project: Cohort Team Management,1:24,20941,933,14,https://i.ytimg.com/vi/N47ERzX3odo/mqdefault.jpg,None,Project: Cohort Team Management
28,Rwm2IQa0Lvs,Chai pe charcha ☕️,1:52:17,20312,1064,22,https://i.ytimg.com/vi/Rwm2IQa0Lvs/mqdefault.jpg,None,For DevOps: https://hitesh.ai/devops-cohort\nF...
29,04P-UpcByYs,Project : Squad Up 😎,1:22,19595,885,12,https://i.ytimg.com/vi/04P-UpcByYs/mqdefault.jpg,None,Project : Squad Up 😎
30,7_hXtlT7GtM,"The Chai theme has reached a milestone of 100,...",1:45,30911,2710,58,https://i.ytimg.com/vi/7_hXtlT7GtM/mqdefault.jpg,None,"The Chai theme has reached a milestone of 100,..."
31,hcBWSqytPeY,Prioritize Health First,00:56,52380,2958,28,https://i.ytimg.com/vi/hcBWSqytPeY/mqdefault.jpg,None,Prioritize Health First 😃
32,ueP2PHK3w2s,Full stack data science cohort | Live classes ...,1:30,40462,1811,30,https://i.ytimg.com/vi/ueP2PHK3w2s/mqdefault.jpg,None,
33,foGklduxhM0,FastAPI crash course in Hindi,24:12,84162,4047,1345,https://i.ytimg.com/vi/foGklduxhM0/mqdefault.jpg,"coding, hindi, javascript, web developer, reac...",Our new Live cohorts\nhttps://hitesh.ai/data-s...
34,iSNvKaVtwTU,Talking to a course pirate on call,16:47,116822,6420,962,https://i.ytimg.com/vi/iSNvKaVtwTU/mqdefault.jpg,"coding, hindi, javascript, web developer, reac...",This video should not exists.\nFOCUS on learni...
35,4BQMKkq1T5E,600K special Live ☕️,1:10:20,16509,1145,42,https://i.ytimg.com/vi/4BQMKkq1T5E/mqdefault.jpg,None,https://hitesh.ai/data-science\nhttps://hitesh...
36,tuXgFeRBvVs,Chai pe charcha GenAI ki,1:31:3,19731,908,32,https://i.ytimg.com/vi/tuXgFeRBvVs/mqdefault.jpg,None,https://hitesh.ai/genai-cohort \nhttps://hites...
37,Fw3FezexzV0,"100 free seats every month, DSA sheet, Live cl...",00:00:00,29273,1438,129,https://i.ytimg.com/vi/Fw3FezexzV0/mqdefault.jpg,"coding, hindi, javascript, web developer, reac...",Ye ha hamara CodingHero V2.\nHappy to announce...
38,Kjd-SWpe1do,Full Stack data science cohort | Live batch,26:29,95767,1112,234,https://i.ytimg.com/vi/Kjd-SWpe1do/mqdefault.jpg,"coding, hindi, javascript, web developer, reac...",https://hitesh.ai/data-science\nUse DISCORD25 ...
39,oBLpqSHc3lA,DevOps for Developers cohort | Live classes la...,19:2,112559,1073,194,https://i.ytimg.com/vi/oBLpqSHc3lA/mqdefault.jpg,"coding, hindi, javascript, web developer, reac...",https://hitesh.ai/devops-cohort\nfor 1st 100 u...
40,05WtC2Czc5c,GenAI for developers,1:27,16328,1064,19,https://i.ytimg.com/vi/05WtC2Czc5c/mqdefault.jpg,None,
41,9vqlZneYq7w,Late night stream | just tech talks,37:32,15297,1135,38,https://i.ytimg.com/vi/9vqlZneYq7w/mqdefault.jpg,None,https://hitesh.ai/genai-cohort - GenAI for dev...
42,VNb_LawBBWU,GenAI for developers cohort launch,13:19,146761,1996,356,https://i.ytimg.com/vi/VNb_LawBBWU/mqdefault.jpg,"coding, hindi, javascript, web developer, reac...",https://hitesh.ai/genai-cohort\nuse code HITES...
43,dZyQNy3-HjU,What are MCP servers | Explained in Hindi,26:58,204760,6960,295,https://i.ytimg.com/vi/dZyQNy3-HjU/mqdefault.jpg,"coding, hindi, javascript, web developer, reac...",https://hitesh.ai/cohort\n\nWelcome to chai au...
44,KnIye1fJF80,AI is 90% marketing and 10% reality,11:5,97371,4290,320,https://i.ytimg.com/vi/KnIye1fJF80/mqdefault.jpg,"coding, hindi, javascript, web developer, reac...","Welcome to chai aur code, a coding/programming..."
45,1i8R-iJiEi8,Behind the scene of I build a SAAS with AI,9:31,36542,1900,225,https://i.ytimg.com/vi/1i8R-iJiEi8/mqdefault.jpg,"coding, hindi, javascript, web developer, reac...",https://hitesh.ai/cohort\n\nWelcome to chai au...
46,af62B4lWuLo,Getting attacked from all side,13:25,119075,8291,1048,https://i.ytimg.com/vi/af62B4lWuLo/mqdefault.jpg,"coding, hindi, javascript, web developer, reac...","Welcome to chai aur code, a coding/programming..."
47,RHng5svxT58,AI reviews AI,00:46,9748,372,8,https://i.ytimg.com/vi/RHng5svxT58/mqdefault.jpg,None,
48,07vViFYgysM,AI reviews AI,00:46,16105,866,8,https://i.ytimg.com/vi/07vViFYgysM/mqdefault.jpg,None,
49,bbn6feSeUjI,Chai pe charcha,41:19,21845,1554,61,https://i.ytimg.com/vi/bbn6feSeUjI/mqdefault.jpg,None,https://hitesh.ai/cohort